In [103]:
import pandas as pd

from google.colab import drive

drive.mount ('/content/drive')

origem = '/content/drive/MyDrive/Arquivo_API-2_ONSV/'

arquivo_1 ='acidentes2025_todas_causas_tipos.csv'
arquivo_2 ='acidentes2024_todas_causas_tipos.csv'
arquivo_3 ='acidentes2023_todas_causas_tipos.csv'
arquivo_4 ='acidentes2022_todas_causas_tipos.csv'
arquivo_5 ='acidentes2021_todas_causas_tipos.csv'
arquivo_6 ='acidentes2020_todas_causas_tipos.csv'
arquivo_7 ='acidentes2019_todas_causas_tipos.csv'
arquivo_8 ='acidentes2018_todas_causas_tipos.csv'
arquivo_9 ='acidentes2017_todas_causas_tipos.csv'
arquivo_10 ='anos_16.csv'
arquivo_11 ='anos_15.csv'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [104]:
df_2025 = pd.read_csv(origem + arquivo_1, low_memory=False, sep=';', encoding='latin1', on_bad_lines='skip', quotechar='"')
df_2024 = pd.read_csv(origem + arquivo_2, low_memory=False, sep=';', encoding='latin1', on_bad_lines='skip', quotechar='"')
df_2023 = pd.read_csv(origem + arquivo_3, low_memory=False, sep=';', encoding='latin1', on_bad_lines='skip', quotechar='"')
df_2022 = pd.read_csv(origem + arquivo_4, low_memory=False, sep=';', encoding='latin1', on_bad_lines='skip', quotechar='"')
df_2021 = pd.read_csv(origem + arquivo_5, low_memory=False, sep=';', encoding='latin1', on_bad_lines='skip', quotechar='"')
df_2020 = pd.read_csv(origem + arquivo_6, low_memory=False, sep=';', encoding='latin1', on_bad_lines='skip', quotechar='"')
df_2019 = pd.read_csv(origem + arquivo_7, low_memory=False, sep=';', encoding='latin1', on_bad_lines='skip', quotechar='"')
df_2018 = pd.read_csv(origem + arquivo_8, low_memory=False, sep=';', encoding='latin1', on_bad_lines='skip', quotechar='"')
df_2017 = pd.read_csv(origem + arquivo_9, low_memory=False, sep=';', encoding='latin1', on_bad_lines='skip', quotechar='"')

In [105]:
df_2016 = pd.read_csv(origem + arquivo_10, low_memory=False, sep=',', encoding='UTF-8')
df_2015 = pd.read_csv(origem + arquivo_11, low_memory=False, sep=',', encoding='UTF-8')

In [106]:
PRF_FINAL = pd.concat([df_2017, df_2018, df_2019, df_2020, df_2021, df_2022, df_2023, df_2024, df_2025])

In [107]:
PRF_FINAL_15_16 = pd.concat([df_2015, df_2016,])

In [108]:
import pandas as pd

# Itera sobre as colunas do DataFrame para aplicar fillna condicionalmente
for col in PRF_FINAL_15_16.columns:
    if pd.api.types.is_numeric_dtype(PRF_FINAL_15_16[col]):
        # Se a coluna for numérica (incluindo Int64Dtype), preenche NaNs com 0
        PRF_FINAL_15_16[col] = PRF_FINAL_15_16[col].fillna(0)
    else:
        # Se a coluna não for numérica (por exemplo, objeto/string), preenche NaNs com 'Não Informado'
        PRF_FINAL_15_16[col] = PRF_FINAL_15_16[col].fillna('Não Informado')

print("Valores 'NaN' substituídos por 'Não Informado' em colunas de texto e por 0 em colunas numéricas de PRF_FINAL_15_16.")

Valores 'NaN' substituídos por 'Não Informado' em colunas de texto e por 0 em colunas numéricas de PRF_FINAL_15_16.

In [109]:
PRF_FINAL['tipo_veiculo'] = PRF_FINAL['tipo_veiculo'].replace({
    'Microônibus': 'Micro-ônibus',
    'Motor-Casa': 'Motor-casa',
    'Carro-de-mao': 'Carro-de-mão',
    'Carro de mão': 'Carro-de-mão', #usamos - Para cobrir a variação com espaço
    'Semi-Reboque': 'Semi-reboque',
    'Semireboque': 'Semi-reboque',
    '(null)': 'Não Informado',
})

print("Valores da coluna 'tipo_veiculo' padronizados com sucesso.")
print("Novos valores únicos:")
print(PRF_FINAL['tipo_veiculo'].unique())

Valores da coluna 'tipo_veiculo' padronizados com sucesso.
Novos valores únicos:
['Motocicleta' 'Automóvel' 'Motoneta' nan 'Caminhão' 'Caminhonete'
 'Utilitário' 'Camioneta' 'Caminhão-trator' 'Carroça-charrete' 'Bicicleta'
 'Semi-reboque' 'Reboque' 'Micro-ônibus' 'Ônibus' 'Outros' 'Ciclomotor'
 'Trator de rodas' 'Trator misto' 'Motor-casa' 'Carro-de-mão' 'Trem-bonde'
 'Triciclo' 'Trator de esteira' 'Chassi-plataforma' 'Quadriciclo']

In [110]:
print("Valores únicos da coluna 'tipo_veiculo' em PRF_FINAL_15_16 ANTES da padronização:")
print(PRF_FINAL_15_16['tipo_veiculo'].unique())

# Aplicar .astype(str).str.strip() antes de replace para lidar com espaços e tipos
PRF_FINAL_15_16['tipo_veiculo'] = PRF_FINAL_15_16['tipo_veiculo'].astype(str).str.strip().replace({
    'Motocicletas': 'Motocicleta',
    'Não identificado': 'Não Informado',
    'Microônibus': 'Micro-ônibus',
    'Motor-Casa': 'Motor-casa',
    'Carro-de-mao': 'Carro-de-mão',
    'Carro de mão': 'Carro-de-mão',
    'Semi-Reboque': 'Semi-reboque',
    'Semireboque': 'Semi-reboque',
    '(null)': 'Não Informado',
})

print("\nValores da coluna 'tipo_veiculo' em PRF_FINAL_15_16 padronizados com sucesso.")
print("Novos valores únicos APÓS a padronização:")
print(PRF_FINAL_15_16['tipo_veiculo'].unique())

# Se houver outros valores que você gostaria de padronizar, por favor, me avise!

Valores únicos da coluna 'tipo_veiculo' em PRF_FINAL_15_16 ANTES da padronização:
['Automóvel' 'Utilitário' 'Caminhão' 'Motocicletas' 'Caminhão-Trator'
 'Camioneta' 'Ônibus' '(null)' 'Ciclomotor' 'Caminhonete' 'Motoneta'
 'Não identificado' 'Microônibus' 'Bicicleta' 'Semi-Reboque'
 'Caminhão-Tanque' 'Charrete' 'Trator de rodas' 'Reboque' 'Carroça'
 'Trator de esteiras' 'Triciclo' 'Carro-de-mao' 'Trator misto'
 'Bonde / Trem' 'Quadriciclo' 'Motor-Casa' 'Não Informado']

Valores da coluna 'tipo_veiculo' em PRF_FINAL_15_16 padronizados com sucesso.
Novos valores únicos APÓS a padronização:
['Automóvel' 'Utilitário' 'Caminhão' 'Motocicleta' 'Caminhão-Trator'
 'Camioneta' 'Ônibus' 'Não Informado' 'Ciclomotor' 'Caminhonete'
 'Motoneta' 'Micro-ônibus' 'Bicicleta' 'Semi-reboque' 'Caminhão-Tanque'
 'Charrete' 'Trator de rodas' 'Reboque' 'Carroça' 'Trator de esteiras'
 'Triciclo' 'Carro-de-mão' 'Trator misto' 'Bonde / Trem' 'Quadriciclo'
 'Motor-casa']

In [111]:
import pandas as pd

# Itera sobre as colunas do DataFrame para aplicar fillna condicionalmente
for col in PRF_FINAL.columns:
    if pd.api.types.is_numeric_dtype(PRF_FINAL[col]):
        # Se a coluna for numérica, preenche NaNs com 0
        PRF_FINAL[col] = PRF_FINAL[col].fillna(0)
    else:
        # Se a coluna não for numérica (por exemplo, objeto/string), preenche NaNs com 'Não Informado'
        PRF_FINAL[col] = PRF_FINAL[col].fillna('Não Informado')

print("Valores 'NaN' substituídos por 'Não Informado' em colunas de texto e por 0 em colunas numéricas de PRF_FINAL.")

Valores 'NaN' substituídos por 'Não Informado' em colunas de texto e por 0 em colunas numéricas de PRF_FINAL.

In [112]:
import pandas as pd

# Verificar se a coluna 'data_inversa' existe antes de tentar processá-la
if 'data_inversa' in PRF_FINAL.columns:
    PRF_FINAL['data'] = pd.to_datetime(PRF_FINAL['data_inversa'], errors='coerce', dayfirst=False)
    # Para o caso de alguns arquivos serem DD/MM/YYYY, tentar inferir automaticamente
    # Se houver valores que não foram convertidos, tenta novamente com dayfirst=True
    mask_na = PRF_FINAL['data'].isna()
    PRF_FINAL.loc[mask_na, 'data'] = pd.to_datetime(PRF_FINAL.loc[mask_na, 'data_inversa'], errors='coerce', dayfirst=True)

    PRF_FINAL = PRF_FINAL.drop(columns=['data_inversa'])

    print("Coluna 'data_inversa' convertida para o formato de data padrão e renomeada para 'data'.")
else:
    print("Coluna 'data_inversa' não encontrada em PRF_FINAL. É possível que já tenha sido processada ou renomeada.")
    if 'data' in PRF_FINAL.columns:
        print("A coluna 'data' já existe. Nenhuma ação adicional é necessária para conversão de data.")
    else:
        print("Erro: Nem 'data_inversa' nem 'data' foram encontradas. Por favor, verifique a criação de PRF_FINAL e os nomes das colunas.")

Coluna 'data_inversa' convertida para o formato de data padrão e renomeada para 'data'.

In [113]:
def categorizar_veiculo(tipo):
    tipo_lower = str(tipo).lower().strip()
    if tipo_lower in ['automóvel', 'utilitário', 'camioneta', 'caminhonete', 'motor-casa']:
        return 'Transporte Utilitário e Familiar'
    elif tipo_lower in ['ônibus', 'micro-ônibus', 'bonde / trem', 'trem-bonde']:
        return 'Transporte Coletivo'
    elif tipo_lower in ['motocicletas', 'ciclomotor', 'motoneta', 'motocicleta','triciclo','quadriciclo']:
        return 'Duas e Quatro Rodas Leves'
    elif tipo_lower in ['caminhão', 'caminhão-trator', 'semi-reboque', 'caminhão-tanque', 'reboque', 'chassi-plataforma']:
        return 'Carga e Transporte Pesado'
    elif tipo_lower == 'bicicleta':
        return 'Não Motorizados'
    elif tipo_lower in ['charrete', 'carroça', 'carro-de-mão', 'carroça-charrete', 'outros']:
        return 'Tração Animal e Outros'
    elif tipo_lower in ['trator de rodas', 'trator de esteiras', 'trator misto', 'trator de esteira']:
        return 'Máquinas Agrícolas e de Construção'
    elif tipo_lower in ['não informado', 'não identificado']:
        return 'Erros ou dados faltantes'
    else:
        return 'Outros/Não Classificado'

PRF_FINAL['categorias'] = PRF_FINAL['tipo_veiculo'].apply(categorizar_veiculo)

print("Coluna 'categorias' criada com sucesso para PRF_FINAL.")
print("Novas categorias em PRF_FINAL:")
print(PRF_FINAL['categorias'].unique())
display(PRF_FINAL.head())

# Aplicar a categorização ao PRF_FINAL_15_16
PRF_FINAL_15_16['categorias'] = PRF_FINAL_15_16['tipo_veiculo'].apply(categorizar_veiculo)

print("\nColuna 'categorias' criada com sucesso para PRF_FINAL_15_16.")
print("Novas categorias em PRF_FINAL_15_16:")
print(PRF_FINAL_15_16['categorias'].unique())
display(PRF_FINAL_15_16.head())

Coluna 'categorias' criada com sucesso para PRF_FINAL.
Novas categorias em PRF_FINAL:
['Duas e Quatro Rodas Leves' 'Transporte Utilitário e Familiar'
 'Erros ou dados faltantes' 'Carga e Transporte Pesado'
 'Tração Animal e Outros' 'Não Motorizados' 'Transporte Coletivo'
 'Máquinas Agrícolas e de Construção']

,id,pesid,dia_semana,horario,uf,br,km,municipio,causa_principal,causa_acidente,ordem_tipo_acidente,tipo_acidente,classificacao_acidente,fase_dia,sentido_via,condicao_metereologica,tipo_pista,tracado_via,uso_solo,id_veiculo,tipo_veiculo,marca,ano_fabricacao_veiculo,tipo_envolvido,estado_fisico,idade,sexo,ilesos,feridos_leves,feridos_graves,mortos,latitude,longitude,regional,delegacia,uop,data,categorias
0,8.0,1.0,domingo,00:00:00,PR,376.0,112,PARANAVAI,Sim,Fenômenos da Natureza,1,Queda de ocupante de veículo,Com Vítimas Feridas,Plena Noite,Crescente,Chuva,Simples,Reta,Não,5.0,Motocicleta,HONDA/CG 150 TITAN ESD,2005.0,Condutor,Lesões Graves,19.0,Masculino,0.0,0.0,1.0,0.0,"-23,09880731","-52,38789369",SPRF-PR,DEL07-PR,UOP02-DEL09-PR,2017-01-01,Duas e Quatro Rodas Leves
1,9.0,955.0,domingo,00:01:00,SC,101.0,234,PALHOCA,Sim,Falta de Atenção à Condução,1,Colisão com objeto estático,Sem Vítimas,Plena Noite,Crescente,Chuva,Dupla,Curva,Não,7.0,Automóvel,FIAT/PALIO WEEKEND EX,2003.0,Condutor,Ileso,35.0,Masculino,1.0,0.0,0.0,0.0,"-27,8101","-48,6357",SPRF-SC,DEL01-SC,UOP02-DEL01-SC,2017-01-01,Transporte Utilitário e Familiar
2,11.0,2.0,domingo,00:00:00,PR,153.0,"56,9",SANTO ANTONIO DA PLATINA,Sim,Animais na Pista,1,Capotamento,Com Vítimas Feridas,Plena Noite,Decrescente,Garoa/Chuvisco,Simples,Reta,Não,6.0,Automóvel,VW/NOVO GOL 1.0,2013.0,Condutor,Lesões Leves,27.0,Feminino,0.0,1.0,0.0,0.0,"-23,36951985","309,93513107",SPRF-PR,DEL07-PR,UOP04-DEL07-PR,2017-01-01,Transporte Utilitário e Familiar
3,11.0,3.0,domingo,00:00:00,PR,153.0,"56,9",SANTO ANTONIO DA PLATINA,Sim,Animais na Pista,1,Capotamento,Com Vítimas Feridas,Plena Noite,Decrescente,Garoa/Chuvisco,Simples,Reta,Não,6.0,Automóvel,VW/NOVO GOL 1.0,2013.0,Passageiro,Lesões Leves,27.0,Masculino,0.0,1.0,0.0,0.0,"-23,36951985","309,93513107",SPRF-PR,DEL07-PR,UOP04-DEL07-PR,2017-01-01,Transporte Utilitário e Familiar
4,12.0,1499.0,domingo,00:00:00,GO,153.0,435,ANAPOLIS,Sim,Avarias e/ou desgaste excessivo no pneu,1,Tombamento,Com Vítimas Feridas,Plena Noite,Decrescente,Céu Claro,Dupla,Reta,Sim,8.0,Motocicleta,KASINSKI/COMET 250,2011.0,Condutor,Lesões Graves,24.0,Masculino,0.0,0.0,1.0,0.0,"-16,27473677","-48,96908998",SPRF-GO,DEL02-GO,UOP01-DEL02-GO,2017-01-01,Duas e Quatro Rodas Leves

Coluna 'categorias' criada com sucesso para PRF_FINAL_15_16.
Novas categorias em PRF_FINAL_15_16:
['Transporte Utilitário e Familiar' 'Carga e Transporte Pesado'
 'Duas e Quatro Rodas Leves' 'Transporte Coletivo'
 'Erros ou dados faltantes' 'Não Motorizados' 'Tração Animal e Outros'
 'Máquinas Agrícolas e de Construção']

,id,pesid,id_veiculo,tipo_veiculo,marca,ano_fabricacao_veiculo,tipo_envolvido,estado_fisico,idade,sexo,nacionalidade,naturalidade,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,classificacao_acidente,fase_dia,sentido_via,condicao_metereologica,tipo_pista,tracado_via,uso_solo,ano,pessoas,mortos,feridos_leves,feridos_graves,ilesos,ignorados,feridos,veiculos,categorias
0,83298209,5085680,18797155,Automóvel,FORD/FIESTA HA 1.6L SE A,2013,Condutor,Ileso,31.0,Feminino,Brasil,Não Informado,2015-01-01,Quinta,00:05:00,RJ,101,327.0,NITEROI,Outras,Colisão traseira,Sem Vítimas,Plena noite,Decrescente,Ceu Claro,Dupla,Reta,Urbano,2015.0,2,0,0,0,2,0,0,2,Transporte Utilitário e Familiar
1,83298209,5085683,18797156,Automóvel,VW/PARATI GLI 1.8 ...,1996,Condutor,Ileso,54.0,Masculino,Brasil,Não Informado,2015-01-01,Quinta,00:05:00,RJ,101,327.0,NITEROI,Outras,Colisão traseira,Sem Vítimas,Plena noite,Decrescente,Ceu Claro,Dupla,Reta,Urbano,2015.0,2,0,0,0,2,0,0,2,Transporte Utilitário e Familiar
2,83298218,5085748,18797180,Automóvel,FIAT/UNO VIVACE 1.0,2014,Condutor,Ileso,45.0,Masculino,Brasil,Ipora,2015-01-01,Quinta,01:20:00,MS,163,434.4,CAMPO GRANDE,Animais na Pista,Saída de Pista,Com Vítimas Feridas,Plena noite,Crescente,Ceu Claro,Simples,Reta,Rural,2015.0,2,0,1,0,1,0,1,1,Transporte Utilitário e Familiar
3,83298218,5085750,18797180,Automóvel,FIAT/UNO VIVACE 1.0,2014,Passageiro,Ferido Leve,52.0,Feminino,Brasil,Belem,2015-01-01,Quinta,01:20:00,MS,163,434.4,CAMPO GRANDE,Animais na Pista,Saída de Pista,Com Vítimas Feridas,Plena noite,Crescente,Ceu Claro,Simples,Reta,Rural,2015.0,2,0,1,0,1,0,1,1,Transporte Utilitário e Familiar
4,83298220,5090792,18799545,Automóvel,VW/POLO SEDAN 1.6,2007,Condutor,Ileso,33.0,Feminino,Brasil,Petropolis,2015-01-01,Quinta,01:45:00,RJ,40,64.0,PETROPOLIS,Outras,Colisão com objeto fixo,Sem Vítimas,Plena noite,Crescente,Nublado,Dupla,Reta,Urbano,2015.0,2,0,0,0,2,0,0,2,Transporte Utilitário e Familiar

In [114]:
MAX_AGE = 100

# Função para tratar idades irrealistas
def tratar_idade_irrealista(df_name, df):
    print(f"Verificando e corrigindo valores de 'idade' no DataFrame: {df_name}")
    if 'idade' in df.columns:
        # Substituir idades maiores que MAX_AGE ou menores que 0 por NaN
        # O fillna subsequente (já implementado em outras células) converterá NaN para 0
        outliers_high = df[df['idade'] > MAX_AGE]['idade'].count()
        outliers_low = df[df['idade'] < 0]['idade'].count()

        if outliers_high > 0:
            df.loc[df['idade'] > MAX_AGE, 'idade'] = pd.NA
            print(f"  - {outliers_high} valores de 'idade' acima de {MAX_AGE} foram substituídos por NA em {df_name}.")
        else:
            print(f"  - Nenhuma idade acima de {MAX_AGE} encontrada em {df_name}.")

        if outliers_low > 0:
            df.loc[df['idade'] < 0, 'idade'] = pd.NA
            print(f"  - {outliers_low} valores de 'idade' abaixo de 0 (incluindo -1) foram substituídos por NA em {df_name}.")
        else:
            print(f"  - Nenhuma idade abaixo de 0 encontrada em {df_name}.")

    else:
        print(f"  - Coluna 'idade' não encontrada em {df_name}.")

# Aplicar a função a ambos os DataFrames
tratar_idade_irrealista('PRF_FINAL', PRF_FINAL)
tratar_idade_irrealista('PRF_FINAL_15_16', PRF_FINAL_15_16)

print("Processo de correção de idades irrealistas concluído. Lembre-se de re-executar as células de `fillna` e `convert_float_to_int_if_applicable` caso não tenha feito após esta alteração para garantir que os NAs sejam convertidos para 0 e o tipo Int64Dtype seja aplicado.")

Verificando e corrigindo valores de 'idade' no DataFrame: PRF_FINAL
  - 5411 valores de 'idade' acima de 100 foram substituídos por NA em PRF_FINAL.
  - 2 valores de 'idade' abaixo de 0 (incluindo -1) foram substituídos por NA em PRF_FINAL.
Verificando e corrigindo valores de 'idade' no DataFrame: PRF_FINAL_15_16
  - 30 valores de 'idade' acima de 100 foram substituídos por NA em PRF_FINAL_15_16.
  - 44991 valores de 'idade' abaixo de 0 (incluindo -1) foram substituídos por NA em PRF_FINAL_15_16.
Processo de correção de idades irrealistas concluído. Lembre-se de re-executar as células de `fillna` e `convert_float_to_int_if_applicable` caso não tenha feito após esta alteração para garantir que os NAs sejam convertidos para 0 e o tipo Int64Dtype seja aplicado.

In [115]:
import pandas as pd

# Lista de colunas que geralmente são números inteiros, mas podem ser floats com '.0'
# Excluindo 'km' conforme solicitado.
integer_like_columns_to_convert = [
    'id', 'pesid', 'id_veiculo', 'ano_fabricacao_veiculo', 'idade',
    'mortos', 'feridos_leves', 'feridos_graves', 'ilesos', 'ignorados',
    'feridos', 'veiculos', 'br', 'ano'
]

def convert_float_to_int_if_applicable(df_name, df):
    print(f"Processando o DataFrame: {df_name}")
    for col in integer_like_columns_to_convert:
        if col in df.columns:
            # Verifica se a coluna é numérica (float) e pode ser convertida para inteiro
            # Usamos pd.Int64Dtype() para permitir valores NaN (missing values) em colunas inteiras
            if pd.api.types.is_float_dtype(df[col]):
                df[col] = df[col].astype(pd.Int64Dtype())
                print(f"  - Coluna '{col}' em {df_name} convertida para Int64Dtype.")
    print(f"Colunas numéricas com '.0' removido em {df_name} (convertidas para tipo inteiro, se aplicável).")

# Aplicar a função para os DataFrames
convert_float_to_int_if_applicable('PRF_FINAL', PRF_FINAL)
convert_float_to_int_if_applicable('PRF_FINAL_15_16', PRF_FINAL_15_16)

print("\nVerifique o .head() ou .info() dos DataFrames para confirmar as alterações e que 'km' manteve seu tipo original.")

Processando o DataFrame: PRF_FINAL
  - Coluna 'id' em PRF_FINAL convertida para Int64Dtype.
  - Coluna 'pesid' em PRF_FINAL convertida para Int64Dtype.
  - Coluna 'id_veiculo' em PRF_FINAL convertida para Int64Dtype.
  - Coluna 'ano_fabricacao_veiculo' em PRF_FINAL convertida para Int64Dtype.
  - Coluna 'idade' em PRF_FINAL convertida para Int64Dtype.
  - Coluna 'mortos' em PRF_FINAL convertida para Int64Dtype.
  - Coluna 'feridos_leves' em PRF_FINAL convertida para Int64Dtype.
  - Coluna 'feridos_graves' em PRF_FINAL convertida para Int64Dtype.
  - Coluna 'ilesos' em PRF_FINAL convertida para Int64Dtype.
  - Coluna 'br' em PRF_FINAL convertida para Int64Dtype.
Colunas numéricas com '.0' removido em PRF_FINAL (convertidas para tipo inteiro, se aplicável).
Processando o DataFrame: PRF_FINAL_15_16
  - Coluna 'idade' em PRF_FINAL_15_16 convertida para Int64Dtype.
  - Coluna 'ano' em PRF_FINAL_15_16 convertida para Int64Dtype.
Colunas numéricas com '.0' removido em PRF_FINAL_15_16 (convertidas para tipo inteiro, se aplicável).

Verifique o .head() ou .info() dos DataFrames para confirmar as alterações e que 'km' manteve seu tipo original.

In [116]:
# Processando o DataFrame PRF_FINAL_15_16 para a coluna 'data_inversa'
if 'data_inversa' in PRF_FINAL_15_16.columns:
    # Tentar converter usando um formato padrão (e.g., YYYY-MM-DD) ou inferir se possível
    PRF_FINAL_15_16['data'] = pd.to_datetime(PRF_FINAL_15_16['data_inversa'], errors='coerce', format='%Y-%m-%d')

    # Identificar valores que falharam na primeira tentativa
    mask_na_15_16 = PRF_FINAL_15_16['data'].isna()

    # Tentar um formato alternativo para os valores que falharam (e.g., DD/MM/YYYY)
    PRF_FINAL_15_16.loc[mask_na_15_16, 'data'] = pd.to_datetime(
        PRF_FINAL_15_16.loc[mask_na_15_16, 'data_inversa'],
        errors='coerce',
        format='%d/%m/%Y'
    )

    # Após a conversão, remover a coluna 'data_inversa' original
    PRF_FINAL_15_16 = PRF_FINAL_15_16.drop(columns=['data_inversa'])
    print("Coluna 'data_inversa' convertida para o formato de data padrão e renomeada para 'data' em PRF_FINAL_15_16.")
else:
    print("Coluna 'data_inversa' não encontrada em PRF_FINAL_15_16. É possível que já tenha sido processada ou renomeada.")
    if 'data' in PRF_FINAL_15_16.columns:
        print("A coluna 'data' já existe em PRF_FINAL_15_16. Nenhuma ação adicional é necessária para conversão de data.")
    else:
        print("Erro: Nem 'data_inversa' nem 'data' foram encontradas em PRF_FINAL_15_16. Por favor, verifique os nomes das colunas.")

Coluna 'data_inversa' convertida para o formato de data padrão e renomeada para 'data' em PRF_FINAL_15_16.

In [117]:
def mapear_gravidade_geral(estado_fisico):
    estado_fisico_lower = str(estado_fisico).lower().strip()
    if estado_fisico_lower == 'óbito' or estado_fisico_lower == 'morto':
        return 'Morte'
    elif estado_fisico_lower == 'lesões graves' or estado_fisico_lower == 'ferido grave':
        return 'Ferido Grave'
    elif estado_fisico_lower == 'lesões leves' or estado_fisico_lower == 'ferido leve':
        return 'Ferido Leve'
    elif estado_fisico_lower == 'ileso':
        return 'Ileso'
    elif estado_fisico_lower in ['não informado', '(null)', 'ignorado']:
        return 'Não Informado'
    else:
        return 'Outros'

# Exibir os valores únicos e suas contagens para 'estado_fisico' antes de aplicar o mapeamento
print("Valores únicos e suas contagens para 'estado_fisico' em PRF_FINAL_15_16:")
print(PRF_FINAL_15_16['estado_fisico'].value_counts(dropna=False))

# Criar a coluna 'gravidade_geral' em PRF_FINAL_15_16
PRF_FINAL_15_16['gravidade_geral'] = PRF_FINAL_15_16['estado_fisico'].apply(mapear_gravidade_geral)
print("\nColuna 'gravidade_geral' criada com sucesso em PRF_FINAL_15_16, com lógica de categorização aprimorada.")

# Exibir as primeiras linhas e contagem de valores para PRF_FINAL_15_16
print("\nPrimeiras linhas de PRF_FINAL_15_16 com a nova coluna 'gravidade_geral':")
display(PRF_FINAL_15_16[['estado_fisico', 'gravidade_geral']].head())
print("Contagem de valores para 'gravidade_geral' em PRF_FINAL_15_16:")
print(PRF_FINAL_15_16['gravidade_geral'].value_counts(dropna=False))

# Adicionar uma verificação explícita para a categoria 'Outros'
if 'Outros' in PRF_FINAL_15_16['gravidade_geral'].unique():
    print(f"ATENÇÃO: A categoria 'Outros' ainda existe na coluna 'gravidade_geral' com {PRF_FINAL_15_16['gravidade_geral'].value_counts()['Outros']} ocorrências. Isso pode indicar valores de `estado_fisico` não mapeados.")
else:
    print("\nNenhuma ocorrência da categoria 'Outros' foi encontrada na coluna 'gravidade_geral'. Todos os valores de 'estado_fisico' foram mapeados para as categorias definidas.")

Valores únicos e suas contagens para 'estado_fisico' em PRF_FINAL_15_16:
estado_fisico
Ileso            159321
Ileso            112305
Ferido Leve       67743
Ferido Leve       65253
Ferido Grave      43931
Ignorado          12612
Ignorado          10883
Morto              6869
Morto              6398
(null)                7
Não Informado         3
Name: count, dtype: int64

Coluna 'gravidade_geral' criada com sucesso em PRF_FINAL_15_16, com lógica de categorização aprimorada.

Primeiras linhas de PRF_FINAL_15_16 com a nova coluna 'gravidade_geral':

  estado_fisico gravidade_geral
0  Ileso                  Ileso
1  Ileso                  Ileso
2  Ileso                  Ileso
3  Ferido Leve      Ferido Leve
4  Ileso                  Ileso

Contagem de valores para 'gravidade_geral' em PRF_FINAL_15_16:
gravidade_geral
Ileso            271626
Ferido Leve      132996
Ferido Grave      43931
Não Informado     23505
Morte             13267
Name: count, dtype: int64

Nenhuma ocorrência da categoria 'Outros' foi encontrada na coluna 'gravidade_geral'. Todos os valores de 'estado_fisico' foram mapeados para as categorias definidas.

In [118]:
print("Valores únicos e suas contagens para 'estado_fisico' em PRF_FINAL_15_16 (após mapeamento da gravidade geral):")
print(PRF_FINAL_15_16['estado_fisico'].value_counts(dropna=False))

Valores únicos e suas contagens para 'estado_fisico' em PRF_FINAL_15_16 (após mapeamento da gravidade geral):
estado_fisico
Ileso            159321
Ileso            112305
Ferido Leve       67743
Ferido Leve       65253
Ferido Grave      43931
Ignorado          12612
Ignorado          10883
Morto              6869
Morto              6398
(null)                7
Não Informado         3
Name: count, dtype: int64

In [119]:
# Padronizar a coluna 'estado_fisico' para remover espaços e capitalização inconsistente
PRF_FINAL_15_16['estado_fisico'] = PRF_FINAL_15_16['estado_fisico'].astype(str).str.strip().str.lower()

print("Coluna 'estado_fisico' padronizada (removendo espaços e convertendo para minúsculas).")

# Exibir os valores únicos e suas contagens após a padronização
print("\nValores únicos e suas contagens para 'estado_fisico' em PRF_FINAL_15_16 (APÓS padronização):")
print(PRF_FINAL_15_16['estado_fisico'].value_counts(dropna=False))

# Reaplicar a função de mapeamento, caso a padronização tenha alterado algum valor que afetasse o mapeamento original
# Isso garante que a coluna 'gravidade_geral' reflita a versão mais limpa de 'estado_fisico'
PRF_FINAL_15_16['gravidade_geral'] = PRF_FINAL_15_16['estado_fisico'].apply(mapear_gravidade_geral)
print("\nColuna 'gravidade_geral' atualizada após a padronização de 'estado_fisico'.")
print("Contagem de valores para 'gravidade_geral' em PRF_FINAL_15_16 (APÓS atualização):")
print(PRF_FINAL_15_16['gravidade_geral'].value_counts(dropna=False))

# Demonstração de como ver apenas os valores de uma categoria específica
categoria_selecionada = 'Morte' # Altere esta variável para ver outras categorias, como 'Ileso', 'Ferido Leve', 'Ferido Grave', 'Não Informado'

print(f"\nExibindo apenas a contagem para a categoria '{categoria_selecionada}' na coluna 'gravidade_geral':")
contagem_categoria_selecionada = PRF_FINAL_15_16[PRF_FINAL_15_16['gravidade_geral'] == categoria_selecionada]['gravidade_geral'].value_counts()
print(contagem_categoria_selecionada)

print(f"\nPara ver outras categorias, basta alterar a variável `categoria_selecionada` (por exemplo, para 'Ileso', 'Ferido Leve', 'Ferido Grave', 'Não Informado').")

Coluna 'estado_fisico' padronizada (removendo espaços e convertendo para minúsculas).

Valores únicos e suas contagens para 'estado_fisico' em PRF_FINAL_15_16 (APÓS padronização):
estado_fisico
ileso            271626
ferido leve      132996
ferido grave      43931
ignorado          23495
morto             13267
(null)                7
não informado         3
Name: count, dtype: int64

Coluna 'gravidade_geral' atualizada após a padronização de 'estado_fisico'.
Contagem de valores para 'gravidade_geral' em PRF_FINAL_15_16 (APÓS atualização):
gravidade_geral
Ileso            271626
Ferido Leve      132996
Ferido Grave      43931
Não Informado     23505
Morte             13267
Name: count, dtype: int64

Exibindo apenas a contagem para a categoria 'Morte' na coluna 'gravidade_geral':
gravidade_geral
Morte    13267
Name: count, dtype: int64

Para ver outras categorias, basta alterar a variável `categoria_selecionada` (por exemplo, para 'Ileso', 'Ferido Leve', 'Ferido Grave', 'Não Informado').

In [123]:
# Identificar colunas com alta porcentagem de valores 'Não Informado' ou nulos

threshold = 0.8 # Definir um limite, por exemplo, 80% de valores vazios/Não Informado

print("Verificando colunas com alta porcentagem de valores 'Não Informado' ou nulos em PRF_FINAL_15_16:")

for col in PRF_FINAL_15_16.columns:
    # Calcular a porcentagem de NaNs
    nan_percentage = PRF_FINAL_15_16[col].isnull().sum() / len(PRF_FINAL_15_16) if not PRF_FINAL_15_16[col].empty else 0

    # Calcular a porcentagem de 'Não Informado' (case-insensitive e trimmed)
    nao_informado_count = PRF_FINAL_15_16[col].astype(str).str.strip().str.lower().eq('não informado').sum()
    nao_informado_percentage = nao_informado_count / len(PRF_FINAL_15_16) if not PRF_FINAL_15_16[col].empty else 0

    # Se a soma das porcentagens ultrapassar o threshold, imprimir
    if (nan_percentage + nao_informado_percentage) > threshold:
        print(f"  - Coluna '{col}': {nan_percentage:.2%} NaN, {nao_informado_percentage:.2%} 'Não Informado'. Total de valores ausentes/não informados: {(nan_percentage + nao_informado_percentage):.2%}")

print("\nSe alguma coluna for listada acima, ela pode ser considerada 'vazia' e podemos discutir a remoção dela se não for relevante para sua análise no Power BI.")

Verificando colunas com alta porcentagem de valores 'Não Informado' ou nulos em PRF_FINAL_15_16:

Se alguma coluna for listada acima, ela pode ser considerada 'vazia' e podemos discutir a remoção dela se não for relevante para sua análise no Power BI.

In [120]:
PRF_FINAL.to_csv(origem+ 'PRF_FINAL.csv', index=False)

In [125]:
PRF_FINAL_15_16.to_csv(origem+ 'PRF_FINAL_15_16.csv', index=False)

In [122]:
pd.set_option('display.max_columns', None)
PRF_FINAL_15_16.head()

,id,pesid,id_veiculo,tipo_veiculo,marca,ano_fabricacao_veiculo,tipo_envolvido,estado_fisico,idade,sexo,nacionalidade,naturalidade,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,classificacao_acidente,fase_dia,sentido_via,condicao_metereologica,tipo_pista,tracado_via,uso_solo,ano,pessoas,mortos,feridos_leves,feridos_graves,ilesos,ignorados,feridos,veiculos,categorias,data,gravidade_geral
0,83298209,5085680,18797155,Automóvel,FORD/FIESTA HA 1.6L SE A,2013,Condutor,ileso,31,Feminino,Brasil,Não Informado,Quinta,00:05:00,RJ,101,327.0,NITEROI,Outras,Colisão traseira,Sem Vítimas,Plena noite,Decrescente,Ceu Claro,Dupla,Reta,Urbano,2015,2,0,0,0,2,0,0,2,Transporte Utilitário e Familiar,2015-01-01,Ileso
1,83298209,5085683,18797156,Automóvel,VW/PARATI GLI 1.8 ...,1996,Condutor,ileso,54,Masculino,Brasil,Não Informado,Quinta,00:05:00,RJ,101,327.0,NITEROI,Outras,Colisão traseira,Sem Vítimas,Plena noite,Decrescente,Ceu Claro,Dupla,Reta,Urbano,2015,2,0,0,0,2,0,0,2,Transporte Utilitário e Familiar,2015-01-01,Ileso
2,83298218,5085748,18797180,Automóvel,FIAT/UNO VIVACE 1.0,2014,Condutor,ileso,45,Masculino,Brasil,Ipora,Quinta,01:20:00,MS,163,434.4,CAMPO GRANDE,Animais na Pista,Saída de Pista,Com Vítimas Feridas,Plena noite,Crescente,Ceu Claro,Simples,Reta,Rural,2015,2,0,1,0,1,0,1,1,Transporte Utilitário e Familiar,2015-01-01,Ileso
3,83298218,5085750,18797180,Automóvel,FIAT/UNO VIVACE 1.0,2014,Passageiro,ferido leve,52,Feminino,Brasil,Belem,Quinta,01:20:00,MS,163,434.4,CAMPO GRANDE,Animais na Pista,Saída de Pista,Com Vítimas Feridas,Plena noite,Crescente,Ceu Claro,Simples,Reta,Rural,2015,2,0,1,0,1,0,1,1,Transporte Utilitário e Familiar,2015-01-01,Ferido Leve
4,83298220,5090792,18799545,Automóvel,VW/POLO SEDAN 1.6,2007,Condutor,ileso,33,Feminino,Brasil,Petropolis,Quinta,01:45:00,RJ,40,64.0,PETROPOLIS,Outras,Colisão com objeto fixo,Sem Vítimas,Plena noite,Crescente,Nublado,Dupla,Reta,Urbano,2015,2,0,0,0,2,0,0,2,Transporte Utilitário e Familiar,2015-01-01,Ileso