In [ ]:
import pandas as pd

from google.colab import drive

drive.mount ('/content/drive')

origem = '/content/drive/My Drive/datasus/'

Mounted at /content/drive

In [ ]:
arquivo_1 = "dt_final_c.csv"

In [ ]:
dt_final_c = pd.read_csv(origem + arquivo_1, low_memory=False, sep=',', encoding='latin1')

In [ ]:
pd.set_option('display.max_columns', None)
dt_final_c.head()

,DTOBITO,HORAOBITO,CODMUNOCOR,CODMUNRES,LOCOCOR,CAUSABAS,SEXO,IDADE,RACACOR,TIPOBITO,ESC2010,OCUP,PESO,NECROPSIA,LINHAA,LINHAB,LINHAC,LINHAD,LINHAII,FONTEINV,ACIDTRAB,fonte_arquivo,ESTCIV
0,12042015,23:30,Não Informado,290500,Via pública,Motociclista traum outr acid transp e NE,Masculino,53 Anos,Não Informado,Não Fetal,Não Informado,Não Informado,NaN,Não Informado,Algumas complic precoces dos traum NCOP,Traum intracraniano,Traum intracraniano,Outr traum da cabeca e os NE,Motociclista traum outr acid transp e NE,Não Informado,Não Informado,DOEXT15.dbc,Não Informado
1,20012015,Não Informado,Não Informado,291010,Domicílio,Auto-intox voluntaria p/alcool,Masculino,43 Anos,Não Informado,Não Fetal,Não Informado,Não Informado,NaN,Não Informado,Outr mortes subitas de causa desconhecida,Desnutric proteico-calorica NE,Auto-intox voluntaria p/alcool,Não Informado,Não Informado,Não Informado,Não Informado,DOEXT15.dbc,Não Informado
2,2012015,12:00,Não Informado,210820,Domicílio,Lesao autoprov intenc enforc estrang sufoc,Masculino,83 Anos,Não Informado,Não Fetal,Não Informado,Não Informado,NaN,Não Informado,Lesao autoprov intenc enforc estrang sufoc,Não Informado,Não Informado,Não Informado,Não Informado,Não Informado,Não Informado,DOEXT15.dbc,Não Informado
3,24122015,19:20,Não Informado,261160,Domicílio,Inalacao do conteudo gastrico,Feminino,92 Anos,Não Informado,Não Fetal,Não Informado,Não Informado,NaN,Não Informado,Inalacao do conteudo gastrico,Sonolencia estupor e coma,Pneumonia p/microorg NE,Não Informado,Hipertensao essencial,Não Informado,Não Informado,DOEXT15.dbc,Não Informado
4,12122015,07:00,Não Informado,150070,Domicílio,Contato c/serpentes e lagartos venenosos,Masculino,9 Anos,Não Informado,Não Fetal,Não Informado,Não Informado,NaN,Não Informado,Outr sint sinais relat ap circulat respirat,Insuf respirat NCOP,Contato c/serpentes e lagartos venenosos,Não Informado,Não Informado,Não Informado,Não Informado,DOEXT15.dbc,Não Informado

In [ ]:
# Definindo palavras-chave em minúsculo relacionadas a acidentes de trânsito
termos_transito = ['transp', 'motociclista', 'pedestre', 'colisao', 'veiculo', 'atropelamento', 'transito', 'ciclista', 'automovel', 'condutor', 'ocupante']

# Criando uma máscara para filtrar a coluna CAUSABAS
mascara = dt_final_c['CAUSABAS'].astype(str).str.lower().str.contains('|'.join(termos_transito), na=False)

# Aplicando o filtro
dt_final_c = dt_final_c[mascara]
dt_final_c.head(1)

,DTOBITO,HORAOBITO,CODMUNOCOR,CODMUNRES,LOCOCOR,CAUSABAS,SEXO,IDADE,RACACOR,TIPOBITO,ESC2010,OCUP,PESO,NECROPSIA,LINHAA,LINHAB,LINHAC,LINHAD,LINHAII,FONTEINV,ACIDTRAB,fonte_arquivo,ESTCIV
0,12042015,23:30,Não Informado,290500,Via pública,Motociclista traum outr acid transp e NE,Masculino,53 Anos,Não Informado,Não Fetal,Não Informado,Não Informado,NaN,Não Informado,Algumas complic precoces dos traum NCOP,Traum intracraniano,Traum intracraniano,Outr traum da cabeca e os NE,Motociclista traum outr acid transp e NE,Não Informado,Não Informado,DOEXT15.dbc,Não Informado

In [ ]:
# Remover a coluna TIPOBITO
dt_final_c = dt_final_c.drop(columns=['TIPOBITO'], errors='ignore')

# Substituir NaN por 'Não Informado'
dt_final_c = dt_final_c.fillna('Não Informado')

# Visualizar o resultado
dt_final_c.head(10)

,DTOBITO,HORAOBITO,CODMUNOCOR,CODMUNRES,LOCOCOR,CAUSABAS,SEXO,IDADE,RACACOR,ESC2010,OCUP,PESO,NECROPSIA,LINHAA,LINHAB,LINHAC,LINHAD,LINHAII,FONTEINV,ACIDTRAB,fonte_arquivo,ESTCIV
0,12042015,23:30,Não Informado,290500,Via pública,Motociclista traum outr acid transp e NE,Masculino,53 Anos,Não Informado,Não Informado,Não Informado,Não Informado,Não Informado,Algumas complic precoces dos traum NCOP,Traum intracraniano,Traum intracraniano,Outr traum da cabeca e os NE,Motociclista traum outr acid transp e NE,Não Informado,Não Informado,DOEXT15.dbc,Não Informado
31,1102015,10:00,Não Informado,520140,Hospital,Ocup automovel traum outr acid transp e NE,Masculino,38 Anos,Não Informado,Não Informado,Não Informado,Não Informado,Não Informado,Não Informado,Pneumonia bacter NCOP,Outr traum do torax e os NE,Ocup automovel traum outr acid transp e NE,Não Informado,Não Informado,Não Informado,DOEXT15.dbc,Não Informado
51,11092015,17:30,Não Informado,210050,Outros,Ocup veic tr pesado traum outr ac transp NE,Masculino,52 Anos,Não Informado,Não Informado,Não Informado,Não Informado,Não Informado,Traum intracraniano,Traum superf da cabeca,Ocup veic tr pesado traum outr ac transp NE,Não Informado,Não Informado,Não Informado,Não Informado,DOEXT15.dbc,Não Informado
53,8032015,13:09,Não Informado,293030,Hospital,Motociclista traum outr acid transp e NE,Masculino,65 Anos,Não Informado,Não Informado,Não Informado,Não Informado,Não Informado,Outr sint sinais relat ap circulat respirat,Traum intracraniano,Algumas complic precoces dos traum NCOP,Motociclista traum outr acid transp e NE,Transt mentais comport dev uso alcool,Não Informado,Não Informado,DOEXT15.dbc,Não Informado
54,6072015,12:20,Não Informado,290390,Outros estabelecimentos de saúde,Acid transp NE,Masculino,31 Anos,Não Informado,Não Informado,Não Informado,Não Informado,Não Informado,Traum intracraniano,Outr sint sinais relat ap circulat respirat,Acid transp NE,Não Informado,Não Informado,Não Informado,Não Informado,DOEXT15.dbc,Não Informado
57,28052015,Não Informado,Não Informado,110012,Via pública,Pedestre traum outr acid transp e NE,Masculino,61 Anos,Não Informado,Não Informado,Não Informado,Não Informado,Não Informado,Insuf respirat NCOP,Asfixia,Pedestre traum outr acid transp e NE,Não Informado,Não Informado,Não Informado,Não Informado,DOEXT15.dbc,Não Informado
59,14092015,Não Informado,Não Informado,110012,Hospital,Ocup automovel traum outr acid transp e NE,Masculino,47 Anos,Não Informado,Não Informado,Não Informado,Não Informado,Não Informado,Traum intracraniano,Outr traum da cabeca e os NE,Ocup automovel traum outr acid transp e NE,Não Informado,Não Informado,Não Informado,Não Informado,DOEXT15.dbc,Não Informado
60,24122015,13:30,Não Informado,150270,Hospital,Acid transp NE,Feminino,52 Anos,Não Informado,Não Informado,Não Informado,Não Informado,Não Informado,Parada cardiaca,Acid transp NE,Não Informado,Não Informado,Não Informado,Não Informado,Não Informado,DOEXT15.dbc,Não Informado
61,2042015,21:00,Não Informado,210580,Via pública,Motociclista traum outr acid transp e NE,Masculino,29 Anos,Não Informado,Não Informado,Não Informado,Não Informado,Não Informado,Motociclista traum outr acid transp e NE,Traum intracraniano,Não Informado,Não Informado,Não Informado,Não Informado,Não Informado,DOEXT15.dbc,Não Informado
62,11042015,17:20,Não Informado,211030,Via pública,Motociclista traum acid transp s/colis,Masculino,49 Anos,Não Informado,Não Informado,Não Informado,Não Informado,Não Informado,Traum intracraniano,Outr traum do pescoco e os NE,Motociclista traum acid transp s/colis,Não Informado,Não Informado,Não Informado,Não Informado,DOEXT15.dbc,Não Informado

In [ ]:
# Removendo a coluna original CODMUNRES
dt_final_c = dt_final_c.drop(columns=['CODMUNRES', 'RACACOR', 'NECROPSIA', 'LINHAD', 'LINHAII', 'fonte_arquivo', 'ESTCIV'], errors='ignore')

# Exibindo as primeiras linhas do DataFrame atualizado
display(dt_final_c.head(5))

,DTOBITO,HORAOBITO,CODMUNOCOR,LOCOCOR,CAUSABAS,SEXO,IDADE,ESC2010,OCUP,PESO,LINHAA,LINHAB,LINHAC,FONTEINV,ACIDTRAB
0,12042015,23:30,Não Informado,Via pública,Motociclista traum outr acid transp e NE,Masculino,53 Anos,Não Informado,Não Informado,Não Informado,Algumas complic precoces dos traum NCOP,Traum intracraniano,Traum intracraniano,Não Informado,Não Informado
31,1102015,10:00,Não Informado,Hospital,Ocup automovel traum outr acid transp e NE,Masculino,38 Anos,Não Informado,Não Informado,Não Informado,Não Informado,Pneumonia bacter NCOP,Outr traum do torax e os NE,Não Informado,Não Informado
51,11092015,17:30,Não Informado,Outros,Ocup veic tr pesado traum outr ac transp NE,Masculino,52 Anos,Não Informado,Não Informado,Não Informado,Traum intracraniano,Traum superf da cabeca,Ocup veic tr pesado traum outr ac transp NE,Não Informado,Não Informado
53,8032015,13:09,Não Informado,Hospital,Motociclista traum outr acid transp e NE,Masculino,65 Anos,Não Informado,Não Informado,Não Informado,Outr sint sinais relat ap circulat respirat,Traum intracraniano,Algumas complic precoces dos traum NCOP,Não Informado,Não Informado
54,6072015,12:20,Não Informado,Outros estabelecimentos de saúde,Acid transp NE,Masculino,31 Anos,Não Informado,Não Informado,Não Informado,Traum intracraniano,Outr sint sinais relat ap circulat respirat,Acid transp NE,Não Informado,Não Informado