In [ ]:
import pandas as pd

from google.colab import drive

drive.mount ('/content/drive')

origem = '/content/drive/My Drive/datasus/'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
arquivo_1 = "dt_final.csv"

In [ ]:
dt_final = pd.read_csv(origem + arquivo_1, low_memory=False, sep=',', encoding='latin1')

In [ ]:
dt_final.head()

,DTOBITO,HORAOBITO,CODMUNOCOR,CODMUNRES,LOCOCOR,CAUSABAS,SEXO,IDADE,RACACOR,TIPOBITO,...,PESO,NECROPSIA,LINHAA,LINHAB,LINHAC,LINHAD,LINHAII,FONTEINV,ACIDTRAB,fonte_arquivo
0,12042015,2330.0,290500,290500,4,V299,1,453,1.0,2,...,NaN,NaN,*T792,*S068,*S069,*S099,*V299,NaN,2.0,DOEXT15.dbc
1,20012015,NaN,290460,291010,3,X659,1,443,1.0,2,...,NaN,NaN,*R960,*E46X,*X659*F102,NaN,NaN,NaN,NaN,DOEXT15.dbc
2,2012015,1200.0,210820,210820,3,X700,1,483,1.0,2,...,NaN,NaN,*X700,NaN,NaN,NaN,NaN,2.0,NaN,DOEXT15.dbc
3,24122015,1920.0,261160,261160,3,W789,2,492,1.0,2,...,NaN,2.0,*W789*T179,*R402,*J189,NaN,*I10X*E149,NaN,NaN,DOEXT15.dbc
4,12122015,700.0,150070,150070,3,X209,1,409,4.0,2,...,NaN,2.0,*R092,*J960,*X209,NaN,NaN,NaN,2.0,DOEXT15.dbc

### Dicionários de Tradução Direta (Variáveis Simples)
Para colunas como `SEXO`, `LOCOCOR` (Local de Ocorrência) e `RACACOR`, você pode definir os dicionários diretamente em Python e transcrever usando a função `.map()` do pandas:

### Extraindo o Dicionário de CID-10 (.zip)
Use o código abaixo para descompactar o arquivo `.zip` diretamente na sua pasta de origem no Google Drive. Ajuste o nome do arquivo `.zip` caso ele tenha sido salvo com um nome diferente de `cid10.zip`.

In [ ]:
import zipfile
import os

# Nome do arquivo zip que você subiu para o seu Drive
nome_arquivo_zip = 'cid10.zip'  # Altere aqui se o nome for diferente
caminho_zip = os.path.join(origem, nome_arquivo_zip)

try:
    with zipfile.ZipFile(caminho_zip, 'r') as zip_ref:
        # Extrai tudo na sua pasta do Drive
        zip_ref.extractall(origem)
    print(f"Arquivo {nome_arquivo_zip} extraído com sucesso em: {origem}")

    # Listar os arquivos extraídos para sabermos qual o arquivo correto
    print("Arquivos extraídos:")
    print(os.listdir(origem))
except FileNotFoundError:
    print(f"Erro: O arquivo '{nome_arquivo_zip}' não foi encontrado na pasta {origem}.")
    print("Por favor, certifique-se de fazer o upload do arquivo .zip para o seu Google Drive nessa pasta.")

Arquivo cid10.zip extraído com sucesso em: /content/drive/My Drive/datasus/
Arquivos extraídos:
['DOEXT15.csv', 'DOEXT16.csv', 'DOEXT17.csv', 'DOEXT18.csv', 'DOEXT19.csv', 'DOEXT20.csv', 'DOEXT21.csv', 'DOEXT22.csv', 'DOEXT23.csv', 'DOEXT24.csv', 'DOEXT25.csv', 'dt_final.csv', 'arquivo.zip', 'datasus_cod.ipynb', 'DD_TABDO.csv', 'cid10.zip', 'OBITOS_CID10_TAB', 'dt_final_transcrito.csv', 'dt_final_completo_transcrito.csv']

In [ ]:
import os

pasta_cid = os.path.join(origem, 'OBITOS_CID10_TAB')
if os.path.exists(pasta_cid):
    print("Arquivos dentro da pasta de CID-10:")
    print(os.listdir(pasta_cid))
else:
    print("Pasta 'OBITOS_CID10_TAB' não foi localizada diretamente. Buscando alternativas...")

Arquivos dentro da pasta de CID-10:
['tabdo', 'tabinf', 'tabmat']

In [ ]:
pasta_tabdo = os.path.join(pasta_cid, 'tabdo')
if os.path.exists(pasta_tabdo):
    print("Arquivos dentro de 'tabdo':")
    print(os.listdir(pasta_tabdo))
else:
    print("Pasta 'tabdo' não foi encontrada.")

Arquivos dentro de 'tabdo':
['.Rprofile', 'ACIDTRA1.CNV', 'ACIDTRAB.CNV', 'ACprior2025.cnv', 'actragrp.cnv', 'AFOGA.CNV', 'ANO.CNV', 'ANO7995.CNV', 'ASSMEDIC.CNV', 'asterisc.cnv', 'ATESTANT.CNV', 'CAPITAIS.CNV', 'CartaoSUS.cnv', 'CAUMATER-rev2025.cnv', 'CAUMATER.cnv', 'CAUMEN.CNV', 'caupresu0509.cnv', 'CAUSABR.CNV', 'CAUSABRA.CNV', 'CAUSACAP.CNV', 'CAUSAMAT1.cnv', 'CAUSASEXCL.cnv', 'CBO2002.CNV', 'CBPoucoUteis.CNV', 'CEXTsb.CNV', 'CID10-Evit0a4.cnv', 'CID10-Evit5a74.cnv', 'CID10-grup_d.cnv', 'CID10-Lista-02.cnv', 'CID10-Lista-04.cnv', 'CID10CAP.CNV', 'CID10_01.CNV', 'CID10_01_ST.CNV', 'CID10_02.CNV', 'CID10_02_ST.CNV', 'CID10_03.CNV', 'CID10_03_ST.CNV', 'CID10_04.CNV', 'CID10_04_ST.CNV', 'CID10_05.CNV', 'CID10_05_ST.CNV', 'CID10_06.CNV', 'CID10_06_ST.CNV', 'CID10_07.CNV', 'CID10_07_ST.CNV', 'CID10_08.CNV', 'CID10_08_ST.CNV', 'CID10_09.CNV', 'CID10_09_ST.CNV', 'CID10_10.CNV', 'CID10_10_ST.CNV', 'CID10_11.CNV', 'CID10_11_ST.CNV', 'CID10_12.CNV', 'CID10_12_ST.CNV', 'CID10_13.CNV', 'CID10_13_ST.CNV', 'CID10_14.CNV', 'CID10_14_ST.CNV', 'CID10_15.CNV', 'CID10_15_ST.CNV', 'CID10_16.CNV', 'CID10_16_ST.CNV', 'CID10_17.CNV', 'CID10_17_ST.CNV', 'CID10_18.CNV', 'CID10_18_ST.CNV', 'CID10_19.cnv', 'CID10_19_ST.cnv', 'CID10_20.CNV', 'CID10_20_ST.CNV', 'CID10_21.cnv', 'CID10_21_ST.cnv', 'CID10_22.cnv', 'CID10_22_ST.cnv', 'CID10_3D.CNV', 'CID10_3Da.CNV', 'CID10_3DN.CNV', 'CID10_BR.CNV', 'CID10_plenamente_alcool.cnv', 'CIDCEXT.CNV', 'CIDFOGO.CNV', 'CID_Hidrica.CNV', 'cinvalid.cnv', 'CIRAC.cnv', 'CIRACC.cnv', 'CIRACN.cnv', 'CIRAL.cnv', 'CIRALC.cnv', 'CIRALN.cnv', 'CIRAM.cnv', 'CIRAMC.cnv', 'CIRAMN.cnv', 'CIRAP.cnv', 'CIRAPC.cnv', 'CIRAPN.cnv', 'CIRBA.cnv', 'CIRBAC.cnv', 'CIRBAN.cnv', 'CIRBR.cnv', 'CIRBRC.cnv', 'CIRBRN.cnv', 'CIRCE.cnv', 'CIRCEC.cnv', 'CIRCEN.cnv', 'CIRDF.cnv', 'CIRDFC.cnv', 'CIRDFN.cnv', 'CIRES.cnv', 'CIRESC.cnv', 'CIRESN.cnv', 'CIRGO.cnv', 'CIRGOC.cnv', 'CIRGON.cnv', 'CIRMA.cnv', 'CIRMAC.cnv', 'CIRMAN.cnv', 'CIRMG.cnv', 'CIRMGC.cnv', 'CIRMGN.cnv', 'CIRMS.cnv', 'CIRMSC.cnv', 'CIRMSN.cnv', 'CIRMT.cnv', 'CIRMTC.cnv', 'CIRMTN.cnv', 'CIRMUAC.cnv', 'CIRMUAL.cnv', 'CIRMUAM.cnv', 'CIRMUAP.cnv', 'CIRMUBA.cnv', 'CIRMUCE.cnv', 'CIRMUDF.cnv', 'CIRMUES.cnv', 'CIRMUGO.cnv', 'CIRMUMA.cnv', 'CIRMUMG.cnv', 'CIRMUMS.cnv', 'CIRMUMT.cnv', 'CIRMUPA.cnv', 'CIRMUPB.cnv', 'CIRMUPE.cnv', 'CIRMUPI.cnv', 'CIRMUPR.cnv', 'CIRMURJ.cnv', 'CIRMURN.cnv', 'CIRMURO.cnv', 'CIRMURR.cnv', 'CIRMURS.cnv', 'CIRMUSC.cnv', 'CIRMUSE.cnv', 'CIRMUSP.cnv', 'CIRMUTO.cnv', 'CIRPA.cnv', 'CIRPAC.cnv', 'CIRPAN.cnv', 'CIRPB.cnv', 'CIRPBC.cnv', 'CIRPBN.cnv', 'CIRPE.cnv', 'CIRPEC.cnv', 'CIRPEN.cnv', 'CIRPI.cnv', 'CIRPIC.cnv', 'CIRPIN.cnv', 'CIRPR.cnv', 'CIRPRC.cnv', 'CIRPRN.cnv', 'CIRRJ.cnv', 'CIRRJC.cnv', 'CIRRJN.cnv', 'CIRRN.cnv', 'CIRRNC.cnv', 'CIRRNN.cnv', 'CIRRO.cnv', 'CIRROC.cnv', 'CIRRON.cnv', 'CIRRR.cnv', 'CIRRRC.cnv', 'CIRRRN.cnv', 'CIRRS.cnv', 'CIRRSC.cnv', 'CIRRSN.cnv', 'CIRSC.cnv', 'CIRSCC.cnv', 'CIRSCN.cnv', 'CIRSE.cnv', 'CIRSEC.cnv', 'CIRSEN.cnv', 'CIRSP.cnv', 'CIRSPC.cnv', 'CIRSPN.cnv', 'CIRTO.cnv', 'CIRTOC.cnv', 'CIRTON.cnv', 'CIRURGIA.CNV', 'CNES24.DBF', 'CNES25.DBF', 'CNES26.DBF', 'CNESDO18.DBF', 'CODIFICA1.cnv', 'CODIFICADO1.cnv', 'CODINST.CNV', 'DIAS.CNV', 'diasINVEST1.cnv', 'dias_notif.cnv', 'DOanodist.cnv', 'DONOVA.CNV', 'DPREMAT1.cnv', 'ESCAGR1.CNV', 'ESCAGR2.cnv', 'ESCSERIE.CNV', 'ESFERA18.cnv', 'ESFERA24.CNV', 'ESFERA25.CNV', 'ESFERA26.CNV', 'ESTCIV.CNV', 'EXAME.CNV', 'FONTEINV.CNV', 'FONTINFO.CNV', 'FXIDAD5.CNV', 'FXIDAD9.CNV', 'FXIDADP.CNV', 'FXIDADP5.CNV', 'FXIDAWHO.CNV', 'FXINFAN1.CNV', 'FXINFAN2.CNV', 'FXPOP2007.cnv', 'FXPOP32009.cnv', 'GRAVIDEZ.CNV', 'GRUPO1.CNV', 'GRUPO2.CNV', 'GRUPO3.CNV', 'GRUPO4.CNV', 'GRUPOCUP.CNV', 'GRUPOSprior2025.cnv', 'HOMICID.CNV', 'IDADE.CNV', 'IDADE2.CNV', 'IDADEMAE.CNV', 'IDADzero.CNV', 'improv.CNV', 'improv1.CNV', 'ImprovaveisSTriviais.CNV', 'IndMortalidade.CNV', 'INSTRUC.CNV', 'INVESTIG.CNV', 'ISQUEM.CNV', 'LOCACID.CNV', 'LOCOCOR.CNV', 'MALDEF.CNV', 'MalDefCBPU.CNV', 'matext_sn.CNV', 'mathers.cnv', 'mdregra_a.cnv', 'MESANO0020.CNV', 'MESES.CNV', 'MICRO.CNV', 'modelDOnum.cnv', 'MuMA8005.cnv', 'MuMA8007.cnv', 'MuME8005.cnv', 'MuME8007.cnv', 'Muni208TMI.cnv', 'MUNICAC.CNV', 'MUNICAL.CNV', 'MUNICAM.CNV', 'MUNICAP.CNV', 'MUNICBA.CNV', 'MUNICBR.CNV', 'MUNICCE.CNV', 'MUNICDF.CNV', 'MUNICES.CNV', 'MUNICGO.CNV', 'MUNICMA.CNV', 'MUNICMG.CNV', 'MUNICMS.CNV', 'MUNICMT.CNV', 'MUNICPA.CNV', 'MUNICPB.CNV', 'MUNICPE.CNV', 'MUNICPI.CNV', 'MUNICPR.CNV', 'MUNICRJ.CNV', 'MUNICRN.CNV', 'MUNICRO.CNV', 'MUNICRR.CNV', 'MUNICRS.CNV', 'MUNICSArido.CNV', 'MUNICSC.CNV', 'MUNICSE.CNV', 'MUNICSP.CNV', 'MUNICTO.CNV', 'MUNIGN.CNV', 'mun_indios.cnv', 'MUN_PT.CNV', 'MUN_ptmen.CNV', 'NAT1213.CNV', 'NATURAL.CNV', 'NECROPS.CNV', 'NEOPLA.CNV', 'NPCB.CNV', 'nuMEROdn.cnv', 'NUMFILH.CNV', 'OBITOFE1.CNV', 'OBITOFE2.CNV', 'obitogra.cnv', 'obitoPUE.cnv', 'Obito_1979_95_CID-09.DEF', 'Obito_1996_CID10.def', 'OCUPA.CNV', 'OCUPACAO.CNV', 'OCUPIGN.CNV', 'OMUFER.CNV', 'oparto.cnv', 'ORIG.CNV', 'PAIS.CNV', 'PARTO.CNV', 'PESO.CNV', 'PESO3.CNV', 'RACACOR.CNV', 'REGIAO.CNV', 'REGIAOC.CNV', 'RETRO.CNV', 'RMETRBR.CNV', 'script.out', 'SEMANAS.CNV', 'SERIEFAL.CNV', 'SEXO.CNV', 'sexoFem.cnv', 'sexoMas.cnv', 'SGESTAC.CNV', 'SGRPOCUP.CNV', 'Subcategoria_CID10.CNV', 'SUICID.CNV', 'TIPOACID.CNV', 'TIPOBITO.CNV', 'TIPOVIOL.CNV', 'TRIVIAL_32.CNV', 'UF.CNV', 'UFC.CNV', 'ufreg.cnv', 'UFSArido.CNV', 'VERSAO.CNV', 'VERSCB.CNV']

In [ ]:
import os
import pandas as pd

def ler_arquivo_cnv(caminho_arquivo):
    """
    Lê um arquivo .cnv do DATASUS e retorna um dicionário mapeando os códigos de CID para suas descrições.
    """
    mapeamento = {}
    try:
        with open(caminho_arquivo, 'r', encoding='latin1') as f:
            linhas = f.readlines()

        # Processa cada linha procurando padrões de conversão
        for linha in linhas:
            linha = linha.strip()
            # Ignora cabeçalhos ou linhas vazias
            if not linha or linha.startswith(';') or linha.upper().startswith('MAPA') or linha.upper().startswith('SEM'):
                continue

            # Linhas válidas do CNV geralmente têm o formato: CODIGO DESCRICAO ou CODIGO;DESCRICAO
            parts = linha.split(' ', 1) if ' ' in linha else linha.split(';', 1)
            if len(parts) == 2:
                codigo = parts[0].strip().replace('"', '')
                descricao = parts[1].strip().replace('"', '')
                mapeamento[codigo] = descricao
    except Exception as e:
        print(f"Erro ao ler o arquivo CNV: {e}")
    return mapeamento

# Caminho do arquivo de CID-10 em 3 dígitos
caminho_cnv = os.path.join(pasta_tabdo, 'CID10_3D.CNV')

if os.path.exists(caminho_cnv):
    dic_cid = ler_arquivo_cnv(caminho_cnv)
    print(f"Sucesso! {len(dic_cid)} termos de CID mapeados do arquivo CNV.")

    # Teste de transcrição no DataFrame para a coluna CAUSABAS
    # Como CAUSABAS muitas vezes tem 4 caracteres (ex: V299), pegamos os 3 primeiros caracteres para bater com o CID10_3D
    dt_final['CAUSABAS_3DIG'] = dt_final['CAUSABAS'].str[:3]
    dt_final['CAUSA_OBITO_DESC'] = dt_final['CAUSABAS_3DIG'].map(dic_cid)

    # Exibe amostra do mapeamento
    display(dt_final[['CAUSABAS', 'CAUSABAS_3DIG', 'CAUSA_OBITO_DESC']].dropna().head(10))
else:
    print(f"O arquivo {caminho_cnv} não foi encontrado.")

Sucesso! 2054 termos de CID mapeados do arquivo CNV.

Empty DataFrame
Columns: [CAUSABAS, CAUSABAS_3DIG, CAUSA_OBITO_DESC]
Index: []

In [ ]:
# 1. Mostrar as primeiras 10 chaves e valores mapeados no dicionário para ver a formatação
chaves_exemplo = list(dic_cid.keys())[:10]
amostra_dic = {k: dic_cid[k] for k in chaves_exemplo}
print("Amostra de chaves e valores do dicionário CNV:")
print(amostra_dic)

# 2. Mostrar alguns valores reais da coluna CAUSABAS para comparação
print("\nAmostra de valores reais da coluna CAUSABAS:")
print(dt_final['CAUSABAS'].dropna().unique()[:10])

Amostra de chaves e valores do dicionário CNV:
{'2054': 'NAO codificada ou em branco                           ,', '1': 'A00   Colera                                       A00,', '2': 'A01   Febres tifoide e paratifoide                 A01,', '3': 'A02   Outr infecc p/Salmonella                     A02,', '4': 'A03   Shiguelose                                   A03,', '5': 'A04   Outr infecc intestinais bacter               A04,', '6': 'A05   Outr intox alimentares bacter NCOP           A05,', '7': 'A06   Amebiase                                     A06,', '8': 'A07   Outr doenc intestinais p/protozoarios        A07,', '9': 'A08   Infecc intestinais virais outr e as NE       A08,'}

Amostra de valores reais da coluna CAUSABAS:
['V299' 'X659' 'X700' 'W789' 'X209' 'W329' 'W699' 'X784' 'W014' 'X477']

In [ ]:
def ler_arquivo_cnv_correto(caminho_arquivo):
    """
    Lê o arquivo .cnv tratando a estrutura interna para extrair o código CID
    e sua respectiva descrição textual.
    """
    mapeamento = {}
    try:
        with open(caminho_arquivo, 'r', encoding='latin1') as f:
            linhas = f.readlines()

        for linha in linhas:
            linha = linha.strip()
            if not linha or linha.startswith(';') or linha.upper().startswith('MAPA') or linha.upper().startswith('SEM'):
                continue

            # Divide a linha: ex '1 A00   Colera                                       A00,'
            # Queremos extrair 'A00' e 'Colera'
            partes_virgula = linha.split(',')
            parte_principal = partes_virgula[0].strip()

            # Divide por múltiplos espaços
            componentes = [c.strip() for c in parte_principal.split('  ') if c.strip()]

            if len(componentes) >= 3:
                # Ex: ['1', 'A00', 'Colera']
                codigo_cid = componentes[1]
                descricao = componentes[2]
                mapeamento[codigo_cid] = descricao
            elif len(componentes) == 2:
                # Ex caso simplificado: ['A00', 'Colera']
                codigo_cid = componentes[0]
                descricao = componentes[1]
                mapeamento[codigo_cid] = descricao
    except Exception as e:
        print(f"Erro ao processar: {e}")
    return mapeamento

# Gerando o novo mapeamento ajustado
dic_cid_correto = ler_arquivo_cnv_correto(caminho_cnv)
print(f"Novos termos mapeados corretamente: {len(dic_cid_correto)}")

# Vamos ver um exemplo do dicionário processado:
exemplo_chaves = list(dic_cid_correto.keys())[:5]
print("Exemplo de mapeamento correto:", {k: dic_cid_correto[k] for k in exemplo_chaves})

# Aplicando a transcrição oficial no DataFrame
dt_final['CAUSABAS_3DIG'] = dt_final['CAUSABAS'].str[:3]
dt_final['CAUSA_OBITO_DESC'] = dt_final['CAUSABAS_3DIG'].map(dic_cid_correto)

# Exibe o resultado final com as traduções das causas
display(dt_final[['CAUSABAS', 'CAUSABAS_3DIG', 'CAUSA_OBITO_DESC']].dropna().head(10))

Novos termos mapeados corretamente: 2054
Exemplo de mapeamento correto: {'A00': 'Colera', 'A01': 'Febres tifoide e paratifoide', 'A02': 'Outr infecc p/Salmonella', 'A03': 'Shiguelose', 'A04': 'Outr infecc intestinais bacter'}

  CAUSABAS CAUSABAS_3DIG                             CAUSA_OBITO_DESC
0     V299           V29     Motociclista traum outr acid transp e NE
1     X659           X65               Auto-intox voluntaria p/alcool
2     X700           X70   Lesao autoprov intenc enforc estrang sufoc
3     W789           W78                Inalacao do conteudo gastrico
4     X209           X20     Contato c/serpentes e lagartos venenosos
5     W329           W32                         Projetil de revolver
6     W699           W69     Afogamento e submersao em aguas naturais
7     X784           X78           Lesao autoprov intenc obj cortante
8     W699           W69     Afogamento e submersao em aguas naturais
9     W014           W01  Queda mesmo nivel escorr tropec passo falso

### Salvando os dados transcritos no Drive
Use o código abaixo para salvar o DataFrame `dt_final` (com as descrições de causas de óbito adicionadas) em um novo arquivo CSV na sua pasta do Google Drive:

### Transcrição Completa das Colunas de `dt_final`

In [ ]:
import numpy as np

# 1. Definição dos Mapeamentos Estáticos (Sexo, Raça/Cor, Local de Ocorrência, Tipo de Óbito)
dic_sexo = {1: 'Masculino', 2: 'Feminino', 0: 'Ignorado', '1': 'Masculino', '2': 'Feminino', '0': 'Ignorado'}

dic_racacor = {
    1: 'Branca', 2: 'Preta', 3: 'Amarela', 4: 'Parda', 5: 'Indígena', 9: 'Ignorado',
    '1': 'Branca', '2': 'Preta', '3': 'Amarela', '4': 'Parda', '5': 'Indígena', '9': 'Ignorado'
}

dic_lococor = {
    1: 'Hospital', 2: 'Outros estabelecimentos de saúde', 3: 'Domicílio',
    4: 'Via pública', 5: 'Outros', 9: 'Ignorado',
    '1': 'Hospital', '2': 'Outros estabelecimentos de saúde', '3': 'Domicílio',
    '4': 'Via pública', '5': 'Outros', '9': 'Ignorado'
}

dic_tipobito = {1: 'Fetal', 2: 'Não Fetal', '1': 'Fetal', '2': 'Não Fetal'}

# Aplicando mapeamentos básicos se as colunas existirem
if 'SEXO' in dt_final.columns:
    dt_final['SEXO_DESC'] = dt_final['SEXO'].map(dic_sexo).fillna('Não Informado')
else:
    dt_final['SEXO_DESC'] = 'Não Informado'

if 'RACACOR' in dt_final.columns:
    dt_final['RACACOR_DESC'] = dt_final['RACACOR'].map(dic_racacor).fillna('Não Informado')
else:
    dt_final['RACACOR_DESC'] = 'Não Informado'

if 'LOCOCOR' in dt_final.columns:
    dt_final['LOCOCOR_DESC'] = dt_final['LOCOCOR'].map(dic_lococor).fillna('Não Informado')
else:
    dt_final['LOCOCOR_DESC'] = 'Não Informado'

if 'TIPOBITO' in dt_final.columns:
    dt_final['TIPOBITO_DESC'] = dt_final['TIPOBITO'].map(dic_tipobito).fillna('Não Informado')
else:
    dt_final['TIPOBITO_DESC'] = 'Não Informado'

# 2. Carregar o arquivo ESTCIV.CNV para obter o Estado Civil de forma dinâmica se a coluna existir
caminho_estciv = os.path.join(pasta_tabdo, 'ESTCIV.CNV')
if 'ESTCIV' in dt_final.columns and os.path.exists(caminho_estciv):
    dic_estciv = ler_arquivo_cnv_correto(caminho_estciv)
    # Garante correspondência tratando strings/inteiros
    dt_final['ESTCIV_DESC'] = dt_final['ESTCIV'].astype(str).str.split('.').str[0].map(dic_estciv).fillna('Não Informado')
else:
    dt_final['ESTCIV_DESC'] = 'Não Informado'

# 3. Transcrever IDADE do padrão DATASUS (onde a primeira casa indica a unidade de tempo: 4=Anos, 3=Meses, 2=Dias...)
def transcrever_idade(cod_idade):
    try:
        cod_str = str(int(float(cod_idade)))
        if len(cod_str) < 3:
            return "Menor de 1 ano"
        prefixo = cod_str[0]
        valor = int(cod_str[1:])
        if prefixo == '4':
            return f"{valor} Anos"
        elif prefixo == '3':
            return f"{valor} Meses"
        elif prefixo == '2':
            return f"{valor} Dias"
        elif prefixo == '1':
            return f"{valor} Horas"
        else:
            return "Idade ignorada"
    except:
        return "Não Informado"

if 'IDADE' in dt_final.columns:
    dt_final['IDADE_DESC'] = dt_final['IDADE'].apply(transcrever_idade)
else:
    dt_final['IDADE_DESC'] = 'Não Informado'

# Exibindo os resultados das transcrições realizadas
colunas_exibicao = [col for col in ['SEXO_DESC', 'RACACOR_DESC', 'LOCOCOR_DESC', 'TIPOBITO_DESC', 'ESTCIV_DESC', 'IDADE_DESC'] if col in dt_final.columns]
display(dt_final[colunas_exibicao].head(10))

,SEXO_DESC,RACACOR_DESC,LOCOCOR_DESC,TIPOBITO_DESC,ESTCIV_DESC,IDADE_DESC
0,Masculino,Não Informado,Via pública,Não Fetal,Não Informado,53 Anos
1,Masculino,Não Informado,Domicílio,Não Fetal,Não Informado,43 Anos
2,Masculino,Não Informado,Domicílio,Não Fetal,Não Informado,83 Anos
3,Feminino,Não Informado,Domicílio,Não Fetal,Não Informado,92 Anos
4,Masculino,Não Informado,Domicílio,Não Fetal,Não Informado,9 Anos
5,Masculino,Não Informado,Domicílio,Não Fetal,Não Informado,16 Anos
6,Feminino,Não Informado,Outros,Não Fetal,Não Informado,6 Anos
7,Masculino,Não Informado,Outros,Não Fetal,Não Informado,15 Anos
8,Masculino,Não Informado,Outros,Não Fetal,Não Informado,27 Anos
9,Masculino,Não Informado,Via pública,Não Fetal,Não Informado,88 Anos

In [ ]:
# 1. Listar todas as colunas presentes no seu DataFrame atual para identificarmos o que falta traduzir
print("Colunas atuais no seu DataFrame (dt_final):")
print(list(dt_final.columns))

# 2. Listar arquivos .CNV de interesse que encontramos na sua pasta 'tabdo' para mapeamentos futuros
arquivos_cnv = [f for f in os.listdir(pasta_tabdo) if f.endswith('.cnv') or f.endswith('.CNV')]
print("\nDicionários (.CNV) disponíveis para tradução:")
for f in sorted(arquivos_cnv):
    # Filtrando alguns dos mais comuns para facilitar a visualização
    if any(palavra in f.upper() for palavra in ['ESC', 'GRAV', 'LOC', 'PART', 'OBITO', 'INSTRU', 'ASSMED']):
        print(f" - {f}")

Colunas atuais no seu DataFrame (dt_final):
['DTOBITO', 'HORAOBITO', 'CODMUNOCOR', 'CODMUNRES', 'LOCOCOR', 'CAUSABAS', 'SEXO', 'IDADE', 'RACACOR', 'TIPOBITO', 'ESC2010', 'OCUP', 'PESO', 'NECROPSIA', 'LINHAA', 'LINHAB', 'LINHAC', 'LINHAD', 'LINHAII', 'FONTEINV', 'ACIDTRAB', 'fonte_arquivo', 'CAUSABAS_3DIG', 'CAUSA_OBITO_DESC', 'SEXO_DESC', 'RACACOR_DESC', 'LOCOCOR_DESC', 'TIPOBITO_DESC', 'ESTCIV_DESC', 'IDADE_DESC']

Dicionários (.CNV) disponíveis para tradução:
 - ASSMEDIC.CNV
 - CIRESC.cnv
 - ESCAGR1.CNV
 - ESCAGR2.cnv
 - ESCSERIE.CNV
 - GRAVIDEZ.CNV
 - INSTRUC.CNV
 - LOCACID.CNV
 - LOCOCOR.CNV
 - OBITOFE1.CNV
 - OBITOFE2.CNV
 - PARTO.CNV
 - TIPOBITO.CNV
 - obitoPUE.cnv
 - obitogra.cnv
 - oparto.cnv

In [ ]:
# 1. Mapeamento de Escolaridade (ESC2010)
dic_esc2010 = {
    '0': 'Sem escolaridade',
    '1': 'Fundamental I (1ª a 4ª série)',
    '2': 'Fundamental II (5ª a 8ª série)',
    '3': 'Ensino Médio',
    '4': 'Ensino Superior incompleto/completo',
    '5': 'Ensino Superior completo',
    '9': 'Ignorado',
    0: 'Sem escolaridade',
    1: 'Fundamental I (1ª a 4ª série)',
    2: 'Fundamental II (5ª a 8ª série)',
    3: 'Ensino Médio',
    4: 'Ensino Superior incompleto/completo',
    5: 'Ensino Superior completo',
    9: 'Ignorado'
}
if 'ESC2010' in dt_final.columns:
    dt_final['ESC2010_DESC'] = dt_final['ESC2010'].map(dic_esc2010).fillna('Não Informado')

# 2. Mapeamento de Necropsia
dic_necropsia = {
    1: 'Sim', 2: 'Não', 9: 'Ignorado',
    '1': 'Sim', '2': 'Não', '9': 'Ignorado'
}
if 'NECROPSIA' in dt_final.columns:
    dt_final['NECROPSIA_DESC'] = dt_final['NECROPSIA'].map(dic_necropsia).fillna('Não Informado')

# 3. Mapeamento de Acidente de Trabalho (ACIDTRAB)
dic_acidtrab = {
    1: 'Sim', 2: 'Não', 9: 'Ignorado',
    '1': 'Sim', '2': 'Não', '9': 'Ignorado'
}
if 'ACIDTRAB' in dt_final.columns:
    dt_final['ACIDTRAB_DESC'] = dt_final['ACIDTRAB'].map(dic_acidtrab).fillna('Não Informado')

# 4. Tradução Dinâmica da Fonte de Investigação (FONTEINV.CNV)
caminho_fonteinv = os.path.join(pasta_tabdo, 'FONTEINV.CNV')
if 'FONTEINV' in dt_final.columns and os.path.exists(caminho_fonteinv):
    dic_fonteinv = ler_arquivo_cnv_correto(caminho_fonteinv)
    dt_final['FONTEINV_DESC'] = dt_final['FONTEINV'].astype(str).str.split('.').str[0].map(dic_fonteinv).fillna('Não Informado')
else:
    dt_final['FONTEINV_DESC'] = 'Não Informado'

# Exibindo os novos resultados transcritos
colunas_novas = [col for col in ['ESC2010_DESC', 'NECROPSIA_DESC', 'ACIDTRAB_DESC', 'FONTEINV_DESC'] if col in dt_final.columns]
display(dt_final[colunas_novas].head(10))

    ESC2010_DESC NECROPSIA_DESC  ACIDTRAB_DESC  FONTEINV_DESC
0  Não Informado  Não Informado  Não Informado  Não Informado
1  Não Informado  Não Informado  Não Informado  Não Informado
2  Não Informado  Não Informado  Não Informado  Não Informado
3  Não Informado  Não Informado  Não Informado  Não Informado
4  Não Informado  Não Informado  Não Informado  Não Informado
5  Não Informado  Não Informado  Não Informado  Não Informado
6  Não Informado  Não Informado  Não Informado  Não Informado
7  Não Informado  Não Informado  Não Informado  Não Informado
8  Não Informado  Não Informado  Não Informado  Não Informado
9  Não Informado  Não Informado  Não Informado  Não Informado

### Salvando a Versão Completamente Transcrita
Agora vamos exportar o novo arquivo CSV contendo todas as descrições decodificadas:

In [ ]:
caminho_final = origem + "dt_final_completo_transcrito.csv"
dt_final.to_csv(caminho_final, index=False, encoding='latin1')
print(f"Arquivo completo salvo com sucesso em: {caminho_final}")

### Etapa 1: Definição de Funções e Mapeamentos Estáticos
Nesta etapa, definimos a função padrão para interpretar os arquivos dicionários do DATASUS (`.CNV`) e criamos as tabelas de tradução para as colunas que possuem mapeamento fixo estruturado.

In [ ]:
import os
import pandas as pd
import numpy as np

def ler_arquivo_cnv_correto(caminho_arquivo):
    """
    Lê arquivos de dicionário .CNV do DATASUS interpretando corretamente
    a estrutura de colunas internas.
    """
    mapeamento = {}
    try:
        with open(caminho_arquivo, 'r', encoding='latin1') as f:
            linhas = f.readlines()
        for linha in linhas:
            linha = linha.strip()
            if not linha or linha.startswith(';') or linha.upper().startswith('MAPA') or linha.upper().startswith('SEM'):
                continue
            partes_virgula = linha.split(',')
            parte_principal = partes_virgula[0].strip()
            componentes = [c.strip() for c in parte_principal.split('  ') if c.strip()]
            if len(componentes) >= 3:
                mapeamento[componentes[1]] = componentes[2]
            elif len(componentes) == 2:
                mapeamento[componentes[0]] = componentes[1]
    except Exception as e:
        print(f"Erro ao processar {caminho_arquivo}: {e}")
    return mapeamento

# --- Mapeamentos Estáticos ---
dic_sexo = {1: 'Masculino', 2: 'Feminino', 0: 'Ignorado', '1': 'Masculino', '2': 'Feminino', '0': 'Ignorado'}

dic_racacor = {
    1: 'Branca', 2: 'Preta', 3: 'Amarela', 4: 'Parda', 5: 'Indígena', 9: 'Ignorado',
    '1': 'Branca', '2': 'Preta', '3': 'Amarela', '4': 'Parda', '5': 'Indígena', '9': 'Ignorado'
}

dic_lococor = {
    1: 'Hospital', 2: 'Outros estabelecimentos de saúde', 3: 'Domicílio',
    4: 'Via pública', 5: 'Outros', 9: 'Ignorado',
    '1': 'Hospital', '2': 'Outros estabelecimentos de saúde', '3': 'Domicílio',
    '4': 'Via pública', '5': 'Outros', '9': 'Ignorado'
}

dic_tipobito = {1: 'Fetal', 2: 'Não Fetal', '1': 'Fetal', '2': 'Não Fetal'}

dic_esc2010 = {
    '0': 'Sem escolaridade', '1': 'Fundamental I (1ª a 4ª série)', '2': 'Fundamental II (5ª a 8ª série)',
    '3': 'Ensino Médio', '4': 'Ensino Superior incompleto/completo', '5': 'Ensino Superior completo', '9': 'Ignorado',
    0: 'Sem escolaridade', 1: 'Fundamental I (1ª a 4ª série)', 2: 'Fundamental II (5ª a 8ª série)',
    3: 'Ensino Médio', 4: 'Ensino Superior incompleto/completo', 5: 'Ensino Superior completo', 9: 'Ignorado'
}

dic_necropsia = {1: 'Sim', 2: 'Não', 9: 'Ignorado', '1': 'Sim', '2': 'Não', '9': 'Ignorado'}

dic_acidtrab = {1: 'Sim', 2: 'Não', 9: 'Ignorado', '1': 'Sim', '2': 'Não', '9': 'Ignorado'}

# Aplicação dos mapeamentos básicos no DataFrame
if 'SEXO' in dt_final.columns:
    dt_final['SEXO_DESC'] = dt_final['SEXO'].map(dic_sexo).fillna('Não Informado')
if 'RACACOR' in dt_final.columns:
    dt_final['RACACOR_DESC'] = dt_final['RACACOR'].map(dic_racacor).fillna('Não Informado')
if 'LOCOCOR' in dt_final.columns:
    dt_final['LOCOCOR_DESC'] = dt_final['LOCOCOR'].map(dic_lococor).fillna('Não Informado')
if 'TIPOBITO' in dt_final.columns:
    dt_final['TIPOBITO_DESC'] = dt_final['TIPOBITO'].map(dic_tipobito).fillna('Não Informado')
if 'ESC2010' in dt_final.columns:
    dt_final['ESC2010_DESC'] = dt_final['ESC2010'].map(dic_esc2010).fillna('Não Informado')
if 'NECROPSIA' in dt_final.columns:
    dt_final['NECROPSIA_DESC'] = dt_final['NECROPSIA'].map(dic_necropsia).fillna('Não Informado')
if 'ACIDTRAB' in dt_final.columns:
    dt_final['ACIDTRAB_DESC'] = dt_final['ACIDTRAB'].map(dic_acidtrab).fillna('Não Informado')

print("Mapeamentos estáticos concluídos!")

Mapeamentos estáticos concluídos!

### Etapa 2: Mapeamentos Dinâmicos (Dicionários `.CNV` do DATASUS)
Carregamos os dados de dicionário para decodificar causas de óbito (CID-10), Estado Civil e Fonte de Investigação diretamente da estrutura extraída.

In [ ]:
# 1. Causas de Óbito (CID-10 3 Dígitos)
caminho_cid10 = os.path.join(pasta_tabdo, 'CID10_3D.CNV')
if os.path.exists(caminho_cid10):
    dic_cid = ler_arquivo_cnv_correto(caminho_cid10)
    dt_final['CAUSABAS_3DIG'] = dt_final['CAUSABAS'].str[:3]
    dt_final['CAUSA_OBITO_DESC'] = dt_final['CAUSABAS_3DIG'].map(dic_cid).fillna('Não Informado')
else:
    dt_final['CAUSA_OBITO_DESC'] = 'Não Informado'

# 2. Estado Civil (ESTCIV.CNV)
caminho_estciv = os.path.join(pasta_tabdo, 'ESTCIV.CNV')
if 'ESTCIV' in dt_final.columns and os.path.exists(caminho_estciv):
    dic_estciv = ler_arquivo_cnv_correto(caminho_estciv)
    dt_final['ESTCIV_DESC'] = dt_final['ESTCIV'].astype(str).str.split('.').str[0].map(dic_estciv).fillna('Não Informado')
else:
    dt_final['ESTCIV_DESC'] = 'Não Informado'

# 3. Fonte da Investigação (FONTEINV.CNV)
caminho_fonteinv = os.path.join(pasta_tabdo, 'FONTEINV.CNV')
if 'FONTEINV' in dt_final.columns and os.path.exists(caminho_fonteinv):
    dic_fonteinv = ler_arquivo_cnv_correto(caminho_fonteinv)
    dt_final['FONTEINV_DESC'] = dt_final['FONTEINV'].astype(str).str.split('.').str[0].map(dic_fonteinv).fillna('Não Informado')
else:
    dt_final['FONTEINV_DESC'] = 'Não Informado'

print("Traduções dinâmicas a partir dos arquivos .CNV concluídas!")

Traduções dinâmicas a partir dos arquivos .CNV concluídas!

### Etapa 3: Tradução da Idade (Padrão DATASUS) e Finalização
Aplicação do decodificador de idade baseado na unidade do tempo do DATASUS (horas, dias, meses e anos).

In [ ]:
def transcrever_idade_datasus(cod_idade):
    try:
        cod_str = str(int(float(cod_idade)))
        if len(cod_str) < 3:
            return "Menor de 1 ano"
        prefixo = cod_str[0]
        valor = int(cod_str[1:])
        if prefixo == '4':
            return f"{valor} Anos"
        elif prefixo == '3':
            return f"{valor} Meses"
        elif prefixo == '2':
            return f"{valor} Dias"
        elif prefixo == '1':
            return f"{valor} Horas"
        else:
            return "Idade ignorada"
    except:
        return "Não Informado"

if 'IDADE' in dt_final.columns:
    dt_final['IDADE_DESC'] = dt_final['IDADE'].apply(transcrever_idade_datasus)
else:
    dt_final['IDADE_DESC'] = 'Não Informado'

print("Processamento das idades finalizado com sucesso!")

Processamento das idades finalizado com sucesso!

### Etapa 4: Exibição do DataFrame Traduzido e Exportação
Abaixo está a tabela unificada e completa com todas as traduções solicitadas aplicadas.

In [ ]:
# 1. Ordenando colunas descritivas mais importantes lado a lado das originais
colunas_visualizar = [
    'DTOBITO', 'CAUSABAS', 'CAUSA_OBITO_DESC', 'SEXO', 'SEXO_DESC',
    'IDADE', 'IDADE_DESC', 'RACACOR', 'RACACOR_DESC', 'LOCOCOR',
    'LOCOCOR_DESC', 'ESC2010', 'ESC2010_DESC', 'NECROPSIA', 'NECROPSIA_DESC'
]

# Filtrando para mostrar apenas as que de fato existem no DataFrame
colunas_visualizar_limpas = [c for c in colunas_visualizar if c in dt_final.columns]

# Mostrando o DataFrame traduzido consolidado
display(dt_final[colunas_visualizar_limpas].head(15))

# 2. Salvando os dados consolidados no seu Google Drive
caminho_completo_csv = os.path.join(origem, 'dt_final_completo_transcrito.csv')
dt_final.to_csv(caminho_completo_csv, index=False, encoding='latin1')
print(f"\nSucesso! Arquivo final completo e totalmente transcrito salvo em: {caminho_completo_csv}")

,DTOBITO,CAUSABAS,CAUSA_OBITO_DESC,SEXO,SEXO_DESC,IDADE,IDADE_DESC,RACACOR,RACACOR_DESC,LOCOCOR,LOCOCOR_DESC,ESC2010,ESC2010_DESC,NECROPSIA,NECROPSIA_DESC
0,12042015,V299,Motociclista traum outr acid transp e NE,1,Masculino,453,53 Anos,1.0,Não Informado,4,Via pública,NaN,Não Informado,NaN,Não Informado
1,20012015,X659,Auto-intox voluntaria p/alcool,1,Masculino,443,43 Anos,1.0,Não Informado,3,Domicílio,NaN,Não Informado,NaN,Não Informado
2,2012015,X700,Lesao autoprov intenc enforc estrang sufoc,1,Masculino,483,83 Anos,1.0,Não Informado,3,Domicílio,NaN,Não Informado,NaN,Não Informado
3,24122015,W789,Inalacao do conteudo gastrico,2,Feminino,492,92 Anos,1.0,Não Informado,3,Domicílio,NaN,Não Informado,2.0,Não Informado
4,12122015,X209,Contato c/serpentes e lagartos venenosos,1,Masculino,409,9 Anos,4.0,Não Informado,3,Domicílio,NaN,Não Informado,2.0,Não Informado
5,28032015,W329,Projetil de revolver,1,Masculino,416,16 Anos,4.0,Não Informado,3,Domicílio,NaN,Não Informado,2.0,Não Informado
6,23082015,W699,Afogamento e submersao em aguas naturais,2,Feminino,406,6 Anos,4.0,Não Informado,5,Outros,NaN,Não Informado,2.0,Não Informado
7,28092015,X784,Lesao autoprov intenc obj cortante,1,Masculino,415,15 Anos,4.0,Não Informado,5,Outros,NaN,Não Informado,NaN,Não Informado
8,5052015,W699,Afogamento e submersao em aguas naturais,1,Masculino,427,27 Anos,5.0,Não Informado,5,Outros,NaN,Não Informado,NaN,Não Informado
9,2012015,W014,Queda mesmo nivel escorr tropec passo falso,1,Masculino,488,88 Anos,4.0,Não Informado,4,Via pública,NaN,Não Informado,NaN,Não Informado
10,26102015,X477,Intox acid outr gases e vapores,1,Masculino,447,47 Anos,4.0,Não Informado,1,Hospital,NaN,Não Informado,2.0,Não Informado
11,23112015,W877,Exposicao a corrente eletrica NE,2,Feminino,440,40 Anos,1.0,Não Informado,5,Outros,NaN,Não Informado,2.0,Não Informado
12,15022015,X931,Agressao disparo de arma de fogo de mao,1,Masculino,423,23 Anos,2.0,Não Informado,3,Domicílio,NaN,Não Informado,9.0,Não Informado
13,18022015,W189,Outr quedas no mesmo nivel,2,Feminino,485,85 Anos,4.0,Não Informado,1,Hospital,NaN,Não Informado,2.0,Não Informado
14,26012015,W740,Afogamento e submersao NE,1,Masculino,401,1 Anos,1.0,Não Informado,3,Domicílio,NaN,Não Informado,NaN,Não Informado

Sucesso! Arquivo final completo e totalmente transcrito salvo em: /content/drive/My Drive/datasus/dt_final_completo_transcrito.csv

In [ ]:
# 1. Substituir os valores diretamente nas colunas originais usando as descrições traduzidas
if 'SEXO_DESC' in dt_final.columns:
    dt_final['SEXO'] = dt_final['SEXO_DESC']
if 'RACACOR_DESC' in dt_final.columns:
    dt_final['RACACOR'] = dt_final['RACACOR_DESC']
if 'LOCOCOR_DESC' in dt_final.columns:
    dt_final['LOCOCOR'] = dt_final['LOCOCOR_DESC']
if 'TIPOBITO_DESC' in dt_final.columns:
    dt_final['TIPOBITO'] = dt_final['TIPOBITO_DESC']
if 'ESTCIV_DESC' in dt_final.columns:
    dt_final['ESTCIV'] = dt_final['ESTCIV_DESC']
if 'IDADE_DESC' in dt_final.columns:
    dt_final['IDADE'] = dt_final['IDADE_DESC']
if 'ESC2010_DESC' in dt_final.columns:
    dt_final['ESC2010'] = dt_final['ESC2010_DESC']
if 'NECROPSIA_DESC' in dt_final.columns:
    dt_final['NECROPSIA'] = dt_final['NECROPSIA_DESC']
if 'ACIDTRAB_DESC' in dt_final.columns:
    dt_final['ACIDTRAB'] = dt_final['ACIDTRAB_DESC']
if 'FONTEINV_DESC' in dt_final.columns:
    dt_final['FONTEINV'] = dt_final['FONTEINV_DESC']
if 'CAUSA_OBITO_DESC' in dt_final.columns:
    dt_final['CAUSABAS'] = dt_final['CAUSA_OBITO_DESC']

# 2. Remover as colunas auxiliares descritivas que foram criadas temporariamente
colunas_para_remover = [
    'SEXO_DESC', 'RACACOR_DESC', 'LOCOCOR_DESC', 'TIPOBITO_DESC',
    'ESTCIV_DESC', 'IDADE_DESC', 'ESC2010_DESC', 'NECROPSIA_DESC',
    'ACIDTRAB_DESC', 'FONTEINV_DESC', 'CAUSABAS_3DIG', 'CAUSA_OBITO_DESC'
]
dt_final = dt_final.drop(columns=[col for col in colunas_para_remover if col in dt_final.columns])

# 3. Visualizar as colunas unificadas e limpas
colunas_principais = ['DTOBITO', 'CAUSABAS', 'SEXO', 'IDADE', 'RACACOR', 'LOCOCOR', 'ESC2010', 'NECROPSIA']
colunas_existentes = [c for c in colunas_principais if c in dt_final.columns]
display(dt_final[colunas_existentes].head(15))

# 4. Salvar os dados consolidados e limpos diretamente no Google Drive
caminho_limpo = os.path.join(origem, 'dt_final_completo_transcrito.csv')
dt_final.to_csv(caminho_limpo, index=False, encoding='latin1')
print(f"\nSucesso! DataFrame limpo e unificado salvo em: {caminho_limpo}")

,DTOBITO,CAUSABAS,SEXO,IDADE,RACACOR,LOCOCOR,ESC2010,NECROPSIA
0,12042015,Motociclista traum outr acid transp e NE,Masculino,53 Anos,Não Informado,Via pública,Não Informado,Não Informado
1,20012015,Auto-intox voluntaria p/alcool,Masculino,43 Anos,Não Informado,Domicílio,Não Informado,Não Informado
2,2012015,Lesao autoprov intenc enforc estrang sufoc,Masculino,83 Anos,Não Informado,Domicílio,Não Informado,Não Informado
3,24122015,Inalacao do conteudo gastrico,Feminino,92 Anos,Não Informado,Domicílio,Não Informado,Não Informado
4,12122015,Contato c/serpentes e lagartos venenosos,Masculino,9 Anos,Não Informado,Domicílio,Não Informado,Não Informado
5,28032015,Projetil de revolver,Masculino,16 Anos,Não Informado,Domicílio,Não Informado,Não Informado
6,23082015,Afogamento e submersao em aguas naturais,Feminino,6 Anos,Não Informado,Outros,Não Informado,Não Informado
7,28092015,Lesao autoprov intenc obj cortante,Masculino,15 Anos,Não Informado,Outros,Não Informado,Não Informado
8,5052015,Afogamento e submersao em aguas naturais,Masculino,27 Anos,Não Informado,Outros,Não Informado,Não Informado
9,2012015,Queda mesmo nivel escorr tropec passo falso,Masculino,88 Anos,Não Informado,Via pública,Não Informado,Não Informado
10,26102015,Intox acid outr gases e vapores,Masculino,47 Anos,Não Informado,Hospital,Não Informado,Não Informado
11,23112015,Exposicao a corrente eletrica NE,Feminino,40 Anos,Não Informado,Outros,Não Informado,Não Informado
12,15022015,Agressao disparo de arma de fogo de mao,Masculino,23 Anos,Não Informado,Domicílio,Não Informado,Não Informado
13,18022015,Outr quedas no mesmo nivel,Feminino,85 Anos,Não Informado,Hospital,Não Informado,Não Informado
14,26012015,Afogamento e submersao NE,Masculino,1 Anos,Não Informado,Domicílio,Não Informado,Não Informado

Sucesso! DataFrame limpo e unificado salvo em: /content/drive/My Drive/datasus/dt_final_completo_transcrito.csv

In [ ]:
# 1. Tradução Dinâmica da coluna de Ocupação (OCUP) utilizando o arquivo CBO2002.CNV
caminho_cbo = os.path.join(pasta_tabdo, 'CBO2002.CNV')

if 'OCUP' in dt_final.columns and os.path.exists(caminho_cbo):
    print("Lendo o arquivo de ocupações CBO2002.CNV...")
    dic_cbo = ler_arquivo_cnv_correto(caminho_cbo)

    # Como os códigos de ocupação podem vir como float ou com pontos, tratamos para o formato string limpo
    dt_final['OCUP_LIMPO'] = dt_final['OCUP'].astype(str).str.split('.').str[0].str.zfill(6)

    # Substituindo diretamente na coluna original pelos textos correspondentes
    dt_final['OCUP'] = dt_final['OCUP_LIMPO'].map(dic_cbo).fillna('Não Informado')

    # Removendo coluna temporária de limpeza
    dt_final = dt_final.drop(columns=['OCUP_LIMPO'])
    print("Tradução da coluna OCUP realizada com sucesso!")
else:
    print("Coluna OCUP ou arquivo CBO2002.CNV não localizados.")

# 2. Visualizar amostra do DataFrame com a ocupação traduzida
colunas_visualizacao = ['DTOBITO', 'CAUSABAS', 'SEXO', 'IDADE', 'OCUP']
colunas_validas = [c for c in colunas_visualizacao if c in dt_final.columns]
display(dt_final[colunas_validas].head(15))

# 3. Salvar novamente a versão atualizada e limpa diretamente no seu Google Drive
dt_final.to_csv(caminho_limpo, index=False, encoding='latin1')
print(f"\nArquivo atualizado salvo com sucesso em: {caminho_limpo}")

Lendo o arquivo de ocupações CBO2002.CNV...
Tradução da coluna OCUP realizada com sucesso!

,DTOBITO,CAUSABAS,SEXO,IDADE,OCUP
0,12042015,Motociclista traum outr acid transp e NE,Masculino,53 Anos,Não Informado
1,20012015,Auto-intox voluntaria p/alcool,Masculino,43 Anos,Não Informado
2,2012015,Lesao autoprov intenc enforc estrang sufoc,Masculino,83 Anos,Não Informado
3,24122015,Inalacao do conteudo gastrico,Feminino,92 Anos,Não Informado
4,12122015,Contato c/serpentes e lagartos venenosos,Masculino,9 Anos,Não Informado
5,28032015,Projetil de revolver,Masculino,16 Anos,Não Informado
6,23082015,Afogamento e submersao em aguas naturais,Feminino,6 Anos,Não Informado
7,28092015,Lesao autoprov intenc obj cortante,Masculino,15 Anos,Não Informado
8,5052015,Afogamento e submersao em aguas naturais,Masculino,27 Anos,Não Informado
9,2012015,Queda mesmo nivel escorr tropec passo falso,Masculino,88 Anos,Não Informado
10,26102015,Intox acid outr gases e vapores,Masculino,47 Anos,Não Informado
11,23112015,Exposicao a corrente eletrica NE,Feminino,40 Anos,Não Informado
12,15022015,Agressao disparo de arma de fogo de mao,Masculino,23 Anos,Não Informado
13,18022015,Outr quedas no mesmo nivel,Feminino,85 Anos,Não Informado
14,26012015,Afogamento e submersao NE,Masculino,1 Anos,Não Informado

Arquivo atualizado salvo com sucesso em: /content/drive/My Drive/datasus/dt_final_completo_transcrito.csv

In [ ]:
import os
import pandas as pd

# 1. Caminho para o arquivo CBO2002.CNV e CADMUN.CNV
caminho_cbo = os.path.join(pasta_tabdo, 'CBO2002.CNV')
caminho_mun = os.path.join(pasta_tabdo, 'CADMUN.CNV')

# Tradução de Ocupação
if 'OCUP' in dt_final.columns and os.path.exists(caminho_cbo):
    print("Lendo o arquivo de ocupações CBO2002.CNV...")
    dic_cbo = ler_arquivo_cnv_correto(caminho_cbo)
    dt_final['OCUP_LIMPO'] = dt_final['OCUP'].astype(str).str.split('.').str[0].str.zfill(6)
    dt_final['OCUP'] = dt_final['OCUP_LIMPO'].map(dic_cbo).fillna('Não Informado')
    dt_final = dt_final.drop(columns=['OCUP_LIMPO'])
    print("Tradução da coluna OCUP realizada com sucesso!")
else:
    print("Coluna OCUP ou dicionário CBO2002.CNV não localizados.")

# Tradução de CODMUNOCOR
if 'CODMUNOCOR' in dt_final.columns and os.path.exists(caminho_mun):
    print("Lendo o dicionário de municípios CADMUN.CNV...")
    dic_mun = ler_arquivo_cnv_correto(caminho_mun)
    dt_final['CODMUNOCOR'] = dt_final['CODMUNOCOR'].astype(str).str.split('.').str[0].map(dic_mun).fillna('Não Informado')
    print("Tradução da coluna CODMUNOCOR realizada com sucesso!")
else:
    print("Coluna CODMUNOCOR ou dicionário CADMUN.CNV não localizados.")

# 2. Exibindo o resultado final do DataFrame unificado, limpo e com texto legível em todas as colunas de interesse
colunas_finais = ['DTOBITO', 'CODMUNOCOR', 'CAUSABAS', 'SEXO', 'IDADE', 'RACACOR', 'LOCOCOR', 'OCUP', 'ESC2010', 'NECROPSIA']
colunas_existentes_finais = [c for c in colunas_finais if c in dt_final.columns]
display(dt_final[colunas_existentes_finais].head(15))

# 3. Exportar a base final definitiva e limpa de volta para o Google Drive
caminho_limpo = os.path.join(origem, 'dt_final_completo_transcrito.csv')
dt_final.to_csv(caminho_limpo, index=False, encoding='latin1')
print(f"\nSucesso! DataFrame final, unificado e limpo salvo em: {caminho_limpo}")

Lendo o arquivo de ocupações CBO2002.CNV...
Tradução da coluna OCUP realizada com sucesso!
Coluna CODMUNOCOR ou dicionário CADMUN.CNV não localizados.

,DTOBITO,CODMUNOCOR,CAUSABAS,SEXO,IDADE,RACACOR,LOCOCOR,OCUP,ESC2010,NECROPSIA
0,12042015,290500,Motociclista traum outr acid transp e NE,Masculino,53 Anos,Não Informado,Via pública,Não Informado,Não Informado,Não Informado
1,20012015,290460,Auto-intox voluntaria p/alcool,Masculino,43 Anos,Não Informado,Domicílio,Não Informado,Não Informado,Não Informado
2,2012015,210820,Lesao autoprov intenc enforc estrang sufoc,Masculino,83 Anos,Não Informado,Domicílio,Não Informado,Não Informado,Não Informado
3,24122015,261160,Inalacao do conteudo gastrico,Feminino,92 Anos,Não Informado,Domicílio,Não Informado,Não Informado,Não Informado
4,12122015,150070,Contato c/serpentes e lagartos venenosos,Masculino,9 Anos,Não Informado,Domicílio,Não Informado,Não Informado,Não Informado
5,28032015,150070,Projetil de revolver,Masculino,16 Anos,Não Informado,Domicílio,Não Informado,Não Informado,Não Informado
6,23082015,150070,Afogamento e submersao em aguas naturais,Feminino,6 Anos,Não Informado,Outros,Não Informado,Não Informado,Não Informado
7,28092015,150070,Lesao autoprov intenc obj cortante,Masculino,15 Anos,Não Informado,Outros,Não Informado,Não Informado,Não Informado
8,5052015,130380,Afogamento e submersao em aguas naturais,Masculino,27 Anos,Não Informado,Outros,Não Informado,Não Informado,Não Informado
9,2012015,292400,Queda mesmo nivel escorr tropec passo falso,Masculino,88 Anos,Não Informado,Via pública,Não Informado,Não Informado,Não Informado
10,26102015,110060,Intox acid outr gases e vapores,Masculino,47 Anos,Não Informado,Hospital,Não Informado,Não Informado,Não Informado
11,23112015,110060,Exposicao a corrente eletrica NE,Feminino,40 Anos,Não Informado,Outros,Não Informado,Não Informado,Não Informado
12,15022015,160050,Agressao disparo de arma de fogo de mao,Masculino,23 Anos,Não Informado,Domicílio,Não Informado,Não Informado,Não Informado
13,18022015,530010,Outr quedas no mesmo nivel,Feminino,85 Anos,Não Informado,Hospital,Não Informado,Não Informado,Não Informado
14,26012015,210580,Afogamento e submersao NE,Masculino,1 Anos,Não Informado,Domicílio,Não Informado,Não Informado,Não Informado

Sucesso! DataFrame final, unificado e limpo salvo em: /content/drive/My Drive/datasus/dt_final_completo_transcrito.csv

In [ ]:
import os

# Localizar arquivos que contêm 'MUN' no nome dentro da pasta tabdo
arquivos_pasta = os.listdir(pasta_tabdo)
arquivos_municipio = [f for f in arquivos_pasta if 'MUN' in f.upper()]
print("Arquivos de município encontrados:", arquivos_municipio)

# Geralmente o arquivo correto é cadmun.cnv ou CADMUN.CNV (case-insensitive)
nome_correto = next((f for f in arquivos_municipio if f.upper() == 'CADMUN.CNV'), None)

if nome_correto:
    caminho_mun_real = os.path.join(pasta_tabdo, nome_correto)
    print(f"Usando o arquivo de municípios: {caminho_mun_real}")
    dic_mun = ler_arquivo_cnv_correto(caminho_mun_real)

    # Como os códigos de municípios no DATASUS costumam ter 6 dígitos, removemos decimais se houver
    dt_final['CODMUNOCOR'] = dt_final['CODMUNOCOR'].astype(str).str.split('.').str[0].map(dic_mun).fillna('Não Informado')
    print("Tradução de CODMUNOCOR realizada com sucesso!")

    # Exibir resultado
    display(dt_final[['DTOBITO', 'CODMUNOCOR', 'CAUSABAS', 'SEXO', 'IDADE']].head(15))

    # Salvar base atualizada
    caminho_limpo = os.path.join(origem, 'dt_final_completo_transcrito.csv')
    dt_final.to_csv(caminho_limpo, index=False, encoding='latin1')
    print(f"Arquivo atualizado salvo em: {caminho_limpo}")
else:
    print("Não foi possível encontrar o arquivo CADMUN.CNV de forma automática.")

Arquivos de município encontrados: ['Muni208TMI.cnv', 'MUNICAC.CNV', 'MUNICAL.CNV', 'MUNICAM.CNV', 'MUNICAP.CNV', 'MUNICBA.CNV', 'MUNICBR.CNV', 'MUNICCE.CNV', 'MUNICDF.CNV', 'MUNICES.CNV', 'MUNICGO.CNV', 'MUNICMA.CNV', 'MUNICMG.CNV', 'MUNICMS.CNV', 'MUNICMT.CNV', 'MUNICPA.CNV', 'MUNICPB.CNV', 'MUNICPE.CNV', 'MUNICPI.CNV', 'MUNICPR.CNV', 'MUNICRJ.CNV', 'MUNICRN.CNV', 'MUNICRO.CNV', 'MUNICRR.CNV', 'MUNICRS.CNV', 'MUNICSArido.CNV', 'MUNICSC.CNV', 'MUNICSE.CNV', 'MUNICSP.CNV', 'MUNICTO.CNV', 'MUNIGN.CNV', 'mun_indios.cnv', 'MUN_PT.CNV', 'MUN_ptmen.CNV']
Não foi possível encontrar o arquivo CADMUN.CNV de forma automática.

In [ ]:
import os
import pandas as pd

caminho_munign = os.path.join(pasta_tabdo, 'MUNIGN.CNV')

if os.path.exists(caminho_munign):
    print("Lendo o dicionário de municípios nacional MUNIGN.CNV...")
    dic_mun = ler_arquivo_cnv_correto(caminho_munign)
    print(f"Sucesso! {len(dic_mun)} municípios mapeados.")

    # Transcrever CODMUNOCOR (tratando códigos numéricos como string de 6 dígitos)
    dt_final['CODMUNOCOR'] = dt_final['CODMUNOCOR'].astype(str).str.split('.').str[0].map(dic_mun).fillna('Não Informado')
    print("Tradução da coluna CODMUNOCOR concluída!")

    # Exibir amostra
    display(dt_final[['DTOBITO', 'CODMUNOCOR', 'CAUSABAS', 'SEXO', 'IDADE']].head(15))

    # Salvar base unificada definitiva atualizada no Drive
    caminho_limpo = os.path.join(origem, 'dt_final_completo_transcrito.csv')
    dt_final.to_csv(caminho_limpo, index=False, encoding='latin1')
    print(f"\nBase de dados final atualizada salva em: {caminho_limpo}")
else:
    print("Arquivo MUNIGN.CNV não foi localizado na pasta 'tabdo'.")

Lendo o dicionário de municípios nacional MUNIGN.CNV...
Sucesso! 29 municípios mapeados.
Tradução da coluna CODMUNOCOR concluída!

,DTOBITO,CODMUNOCOR,CAUSABAS,SEXO,IDADE
0,12042015,Não Informado,Motociclista traum outr acid transp e NE,Masculino,53 Anos
1,20012015,Não Informado,Auto-intox voluntaria p/alcool,Masculino,43 Anos
2,2012015,Não Informado,Lesao autoprov intenc enforc estrang sufoc,Masculino,83 Anos
3,24122015,Não Informado,Inalacao do conteudo gastrico,Feminino,92 Anos
4,12122015,Não Informado,Contato c/serpentes e lagartos venenosos,Masculino,9 Anos
5,28032015,Não Informado,Projetil de revolver,Masculino,16 Anos
6,23082015,Não Informado,Afogamento e submersao em aguas naturais,Feminino,6 Anos
7,28092015,Não Informado,Lesao autoprov intenc obj cortante,Masculino,15 Anos
8,5052015,Não Informado,Afogamento e submersao em aguas naturais,Masculino,27 Anos
9,2012015,Não Informado,Queda mesmo nivel escorr tropec passo falso,Masculino,88 Anos
10,26102015,Não Informado,Intox acid outr gases e vapores,Masculino,47 Anos
11,23112015,Não Informado,Exposicao a corrente eletrica NE,Feminino,40 Anos
12,15022015,Não Informado,Agressao disparo de arma de fogo de mao,Masculino,23 Anos
13,18022015,Não Informado,Outr quedas no mesmo nivel,Feminino,85 Anos
14,26012015,Não Informado,Afogamento e submersao NE,Masculino,1 Anos

Base de dados final atualizada salva em: /content/drive/My Drive/datasus/dt_final_completo_transcrito.csv

In [ ]:
import os
import pandas as pd
import numpy as np

# 1. Formatar HORAOBITO para o padrão HH:MM
def formatar_hora(hora):
    try:
        if pd.isna(hora):
            return "Não Informado"
        # Converte float para string sem decimais
        h_str = str(int(float(hora))).zfill(4)
        if len(h_str) == 4:
            hh = h_str[:2]
            mm = h_str[2:]
            if 0 <= int(hh) < 24 and 0 <= int(mm) < 60:
                return f"{hh}:{mm}"
        return "Não Informado"
    except:
        return "Não Informado"

if 'HORAOBITO' in dt_final.columns:
    print("Formatando coluna HORAOBITO...")
    dt_final['HORAOBITO'] = dt_final['HORAOBITO'].apply(formatar_hora)

# 2. Traduzir CODMUNRES usando CADMUN.CNV se disponível
caminho_mun = os.path.join(pasta_tabdo, 'CADMUN.CNV')
if 'CODMUNRES' in dt_final.columns and os.path.exists(caminho_mun):
    print("Lendo dicionário de municípios CADMUN.CNV...")
    dic_mun = ler_arquivo_cnv_correto(caminho_mun)
    dt_final['CODMUNRES'] = dt_final['CODMUNRES'].astype(str).str.split('.').str[0].map(dic_mun).fillna('Não Informado')

# 3. Traduzir ACIDTRAB utilizando o dicionário ACIDTRAB.CNV
caminho_acid = os.path.join(pasta_tabdo, 'ACIDTRAB.CNV')
if 'ACIDTRAB' in dt_final.columns and os.path.exists(caminho_acid):
    print("Lendo dicionário de acidentes de trabalho ACIDTRAB.CNV...")
    dic_acid = ler_arquivo_cnv_correto(caminho_acid)
    dt_final['ACIDTRAB'] = dt_final['ACIDTRAB'].astype(str).str.split('.').str[0].map(dic_acid).fillna('Não Informado')

# 4. Traduzir as Linhas de Causas da Morte (LINHAA, LINHAB, LINHAC, LINHAD, CODMUNCOR)
# Elas contêm o código CID-10 precedido por asterisco (ex: *T792). Vamos limpar o asterisco e mapear usando o dic_cid_correto.
def traduzir_linha_cid(valor_linha, dicionario_cid):
    try:
        if pd.isna(valor_linha):
            return "Não Informado"
        # Remove o asterisco inicial se houver e pega os 3 primeiros caracteres do CID
        cid_limpo = str(valor_linha).replace('*', '').strip()[:3]
        return dicionario_cid.get(cid_limpo, "Não Informado")
    except:
        return "Não Informado"

linhas_causa = ['LINHAA', 'LINHAB', 'LINHAC', 'LINHAD', 'LINHAII']
for col_linha in linhas_causa:
    if col_linha in dt_final.columns and 'dic_cid_correto' in globals():
        print(f"Traduzindo coluna de causa: {col_linha}...")
        dt_final[col_linha] = dt_final[col_linha].apply(lambda x: traduzir_linha_cid(x, dic_cid_correto))

# 5. Visualizar resultado final consolidado
colunas_visualizar = ['DTOBITO', 'HORAOBITO', 'CODMUNRES', 'ACIDTRAB', 'LINHAA', 'LINHAB', 'LINHAC']
colunas_existentes = [c for c in colunas_visualizar if c in dt_final.columns]
display(dt_final[colunas_existentes].head(15))

# 6. Salvar base de dados atualizada de volta ao Google Drive
caminho_limpo = os.path.join(origem, 'dt_final_completo_transcrito.csv')
dt_final.to_csv(caminho_limpo, index=False, encoding='latin1')
print(f"\nSucesso! Todas as traduções finais concluídas e salvas em: {caminho_limpo}")

Formatando coluna HORAOBITO...
Lendo dicionário de acidentes de trabalho ACIDTRAB.CNV...
Traduzindo coluna de causa: LINHAA...
Traduzindo coluna de causa: LINHAB...
Traduzindo coluna de causa: LINHAC...
Traduzindo coluna de causa: LINHAD...
Traduzindo coluna de causa: LINHAII...

,DTOBITO,HORAOBITO,CODMUNRES,ACIDTRAB,LINHAA,LINHAB,LINHAC
0,12042015,23:30,290500,Não Informado,Algumas complic precoces dos traum NCOP,Traum intracraniano,Traum intracraniano
1,20012015,Não Informado,291010,Não Informado,Outr mortes subitas de causa desconhecida,Desnutric proteico-calorica NE,Auto-intox voluntaria p/alcool
2,2012015,12:00,210820,Não Informado,Lesao autoprov intenc enforc estrang sufoc,Não Informado,Não Informado
3,24122015,19:20,261160,Não Informado,Inalacao do conteudo gastrico,Sonolencia estupor e coma,Pneumonia p/microorg NE
4,12122015,07:00,150070,Não Informado,Outr sint sinais relat ap circulat respirat,Insuf respirat NCOP,Contato c/serpentes e lagartos venenosos
5,28032015,23:59,150070,Não Informado,Parada cardiaca,Hemorragia das vias respirat,Projetil de revolver
6,23082015,16:30,150070,Não Informado,Outr sint sinais relat ap circulat respirat,Afogamento e submersao em aguas naturais,Não Informado
7,28092015,00:00,150070,Não Informado,Parada cardiaca,Lesao autoprov intenc obj cortante,Não Informado
8,5052015,18:00,130380,Não Informado,Afogamento e submersao em aguas naturais,Não Informado,Não Informado
9,2012015,17:22,292400,Não Informado,Choque NCOP,Algumas complic precoces dos traum NCOP,Frat do membro infer nivel NE
10,26102015,16:30,110060,Não Informado,Outr sint sinais relat ap circulat respirat,Insuf respirat NCOP,Afecc resp dev inal prod quim gas fumac vap
11,23112015,11:20,110060,Não Informado,Outr sint sinais relat ap circulat respirat,Não Informado,Não Informado
12,15022015,06:00,160050,Não Informado,Choque NCOP,Agressao disparo de arma de fogo de mao,Não Informado
13,18022015,20:11,530010,Não Informado,Insuf respirat NCOP,Embolia pulmonar,Outr quedas no mesmo nivel
14,26012015,09:30,210580,Não Informado,Afogamento e submersao NE,Não Informado,Não Informado

Sucesso! Todas as traduções finais concluídas e salvas em: /content/drive/My Drive/datasus/dt_final_completo_transcrito.csv

In [ ]:
import os
import pandas as pd

# Carregar a base de dados definitiva com todas as traduções integradas
caminho_completo = os.path.join(origem, 'dt_final_completo_transcrito.csv')

if os.path.exists(caminho_completo):
    dt_final = pd.read_csv(caminho_completo, low_memory=False, encoding='latin1')
    print("Sucesso! DataFrame principal 'dt_final' atualizado com todas as colunas unificadas.")

    # Mostrar colunas unificadas finais relevantes para validação (incluindo LINHAA, LINHAB e LINHAC)
    colunas_validacao = ['DTOBITO', 'HORAOBITO', 'CODMUNRES', 'CAUSABAS', 'SEXO', 'IDADE', 'RACACOR', 'OCUP', 'ACIDTRAB', 'ESC2010', 'LINHAA', 'LINHAB', 'LINHAC']
    colunas_existentes_validacao = [c for c in colunas_validacao if c in dt_final.columns]
    display(dt_final[colunas_existentes_validacao].head(10))
else:
    print(f"Erro: Arquivo {caminho_completo} não localizado.")

Sucesso! DataFrame principal 'dt_final' atualizado com todas as colunas unificadas.

,DTOBITO,HORAOBITO,CODMUNRES,CAUSABAS,SEXO,IDADE,RACACOR,OCUP,ACIDTRAB,ESC2010,LINHAA,LINHAB,LINHAC
0,12042015,23:30,290500,Motociclista traum outr acid transp e NE,Masculino,53 Anos,Não Informado,Não Informado,Não Informado,Não Informado,Algumas complic precoces dos traum NCOP,Traum intracraniano,Traum intracraniano
1,20012015,Não Informado,291010,Auto-intox voluntaria p/alcool,Masculino,43 Anos,Não Informado,Não Informado,Não Informado,Não Informado,Outr mortes subitas de causa desconhecida,Desnutric proteico-calorica NE,Auto-intox voluntaria p/alcool
2,2012015,12:00,210820,Lesao autoprov intenc enforc estrang sufoc,Masculino,83 Anos,Não Informado,Não Informado,Não Informado,Não Informado,Lesao autoprov intenc enforc estrang sufoc,Não Informado,Não Informado
3,24122015,19:20,261160,Inalacao do conteudo gastrico,Feminino,92 Anos,Não Informado,Não Informado,Não Informado,Não Informado,Inalacao do conteudo gastrico,Sonolencia estupor e coma,Pneumonia p/microorg NE
4,12122015,07:00,150070,Contato c/serpentes e lagartos venenosos,Masculino,9 Anos,Não Informado,Não Informado,Não Informado,Não Informado,Outr sint sinais relat ap circulat respirat,Insuf respirat NCOP,Contato c/serpentes e lagartos venenosos
5,28032015,23:59,150070,Projetil de revolver,Masculino,16 Anos,Não Informado,Não Informado,Não Informado,Não Informado,Parada cardiaca,Hemorragia das vias respirat,Projetil de revolver
6,23082015,16:30,150070,Afogamento e submersao em aguas naturais,Feminino,6 Anos,Não Informado,Não Informado,Não Informado,Não Informado,Outr sint sinais relat ap circulat respirat,Afogamento e submersao em aguas naturais,Não Informado
7,28092015,00:00,150070,Lesao autoprov intenc obj cortante,Masculino,15 Anos,Não Informado,Não Informado,Não Informado,Não Informado,Parada cardiaca,Lesao autoprov intenc obj cortante,Não Informado
8,5052015,18:00,130380,Afogamento e submersao em aguas naturais,Masculino,27 Anos,Não Informado,Não Informado,Não Informado,Não Informado,Afogamento e submersao em aguas naturais,Não Informado,Não Informado
9,2012015,17:22,292400,Queda mesmo nivel escorr tropec passo falso,Masculino,88 Anos,Não Informado,Não Informado,Não Informado,Não Informado,Choque NCOP,Algumas complic precoces dos traum NCOP,Frat do membro infer nivel NE