In [2]:
import pandas as pd

from google.colab import drive

drive.mount ('/content/drive')

origem = '/content/drive/My Drive/relação/'

Mounted at /content/drive

In [16]:
arquivo_1 = "PRF_FINAL_15_16.csv"
arquivo_2 = "DATASUS.csv"

In [17]:
prf = pd.read_csv(origem + arquivo_1, low_memory=False, sep=',', encoding='latin1')
dtsus = pd.read_csv(origem + arquivo_2, low_memory=False, sep=',', encoding='latin1')

In [5]:
# Exibindo informações gerais das colunas do DATASUS
print('--- DATASUS Columns & Info ---')
display(dtsus.info())
display(dtsus.head(3))

--- DATASUS Columns & Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 394525 entries, 0 to 394524
Data columns (total 15 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   DTOBITO     394525 non-null  int64
 1   HORAOBITO   394525 non-null  object
 2   CODMUNOCOR  394525 non-null  object
 3   LOCOCOR     394525 non-null  object
 4   CAUSABAS    394525 non-null  object
 5   SEXO        394525 non-null  object
 6   IDADE       394525 non-null  object
 7   ESC2010     394525 non-null  object
 8   OCUP        394525 non-null  object
 9   PESO        394525 non-null  object
 10  LINHAA      394525 non-null  object
 11  LINHAB      394525 non-null  object
 12  LINHAC      394525 non-null  object
 13  FONTEINV    394525 non-null  object
 14  ACIDTRAB    394525 non-null  object
dtypes: int64(1), object(14)
memory usage: 45.1+ MB

None

,DTOBITO,HORAOBITO,CODMUNOCOR,LOCOCOR,CAUSABAS,SEXO,IDADE,ESC2010,OCUP,PESO,LINHAA,LINHAB,LINHAC,FONTEINV,ACIDTRAB
0,12042015,23:30,Não Informado,Via pública,Motociclista traum outr acid transp e NE,Masculino,53 Anos,Não Informado,Não Informado,Não Informado,Algumas complic precoces dos traum NCOP,Traum intracraniano,Traum intracraniano,Não Informado,Não Informado
1,1102015,10:00,Não Informado,Hospital,Ocup automovel traum outr acid transp e NE,Masculino,38 Anos,Não Informado,Não Informado,Não Informado,Não Informado,Pneumonia bacter NCOP,Outr traum do torax e os NE,Não Informado,Não Informado
2,11092015,17:30,Não Informado,Outros,Ocup veic tr pesado traum outr ac transp NE,Masculino,52 Anos,Não Informado,Não Informado,Não Informado,Traum intracraniano,Traum superf da cabeca,Ocup veic tr pesado traum outr ac transp NE,Não Informado,Não Informado

In [6]:
# Exibindo informações gerais das colunas da PRF
print('--- PRF Columns & Info ---')
display(prf.info())
display(prf.head(3))

--- PRF Columns & Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4070595 entries, 0 to 4070594
Data columns (total 38 columns):
 #   Column                  Dtype
---  ------                  -----
 0   id                      int64
 1   pesid                   int64
 2   dia_semana              object
 3   horario                 object
 4   uf                      object
 5   br                      int64
 6   km                      object
 7   municipio               object
 8   causa_principal         object
 9   causa_acidente          object
 10  ordem_tipo_acidente     int64
 11  tipo_acidente           object
 12  classificacao_acidente  object
 13  fase_dia                object
 14  sentido_via             object
 15  condicao_metereologica  object
 16  tipo_pista              object
 17  tracado_via             object
 18  uso_solo                object
 19  id_veiculo              int64
 20  tipo_veiculo            object
 21  marca                   object
 22  ano_fabricacao_veiculo  int64
 23  tipo_envolvido          object
 24  estado_fisico           object
 25  idade                   float64
 26  sexo                    object
 27  ilesos                  int64
 28  feridos_leves           int64
 29  feridos_graves          int64
 30  mortos                  int64
 31  latitude                object
 32  longitude               object
 33  regional                object
 34  delegacia               object
 35  uop                     object
 36  data                    object
 37  categorias              object
dtypes: float64(1), int64(10), object(27)
memory usage: 1.2+ GB

None

,id,pesid,dia_semana,horario,uf,br,km,municipio,causa_principal,causa_acidente,...,feridos_leves,feridos_graves,mortos,latitude,longitude,regional,delegacia,uop,data,categorias
0,8,1,domingo,00:00:00,PR,376,112,PARANAVAI,Sim,FenÃ´menos da Natureza,...,0,1,0,"-23,09880731","-52,38789369",SPRF-PR,DEL07-PR,UOP02-DEL09-PR,2017-01-01,Duas e Quatro Rodas Leves
1,9,955,domingo,00:01:00,SC,101,234,PALHOCA,Sim,Falta de AtenÃ§Ã£o Ã ConduÃ§Ã£o,...,0,0,0,"-27,8101","-48,6357",SPRF-SC,DEL01-SC,UOP02-DEL01-SC,2017-01-01,Transporte UtilitÃ¡rio e Familiar
2,11,2,domingo,00:00:00,PR,153,"56,9",SANTO ANTONIO DA PLATINA,Sim,Animais na Pista,...,1,0,0,"-23,36951985","309,93513107",SPRF-PR,DEL07-PR,UOP04-DEL07-PR,2017-01-01,Transporte UtilitÃ¡rio e Familiar

In [18]:
# 1. Padronização de datas
# DATASUS: DTOBITO está como inteiro (ex: 12042015 -> 12/04/2015)
def formatar_data_dtsus(val):
    s = str(val).zfill(8)
    if len(s) == 8:
        return f"{s[4:8]}-{s[2:4]}-{s[0:2]}"
    return None

dtsus['data_padrao'] = dtsus['DTOBITO'].apply(formatar_data_dtsus)
prf['data_padrao'] = pd.to_datetime(prf['data'], errors='coerce').dt.strftime('%Y-%m-%d')

# 2. Padronização de Idade
# DATASUS: '53 Anos' -> 53
dtsus['idade_padrao'] = dtsus['IDADE'].str.extract('(\d+)').astype(float)
prf['idade_padrao'] = prf['idade'].astype(float)

# 3. Padronização de Sexo
dtsus['sexo_padrao'] = dtsus['SEXO'].astype(str).str.strip().str.upper()
prf['sexo_padrao'] = prf['sexo'].astype(str).str.strip().str.upper()

# 4. Realizando o merge (cruzamento) aproximado com base nas chaves padronizadas
dados_cruzados = pd.merge(
    prf,
    dtsus,
    on=['data_padrao', 'sexo_padrao', 'idade_padrao'],
    how='inner'
)

print(f"Quantidade de registros unificados encontrados: {dados_cruzados.shape[0]}")
display(dados_cruzados.head())

<>:14: SyntaxWarning: invalid escape sequence '\d'
<>:14: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_3936/3925770879.py:14: SyntaxWarning: invalid escape sequence '\d'
  dtsus['idade_padrao'] = dtsus['IDADE'].str.extract('(\d+)').astype(float)

Quantidade de registros unificados encontrados: 205809

,id,pesid,id_veiculo,tipo_veiculo,marca,ano_fabricacao_veiculo,tipo_envolvido,estado_fisico,idade,sexo,nacionalidade,naturalidade,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,classificacao_acidente,fase_dia,sentido_via,condicao_metereologica,tipo_pista,tracado_via,uso_solo,ano,pessoas,mortos,feridos_leves,feridos_graves,ilesos,ignorados,feridos,veiculos,categorias,data,gravidade_geral,data_padrao,idade_padrao,sexo_padrao,DTOBITO,HORAOBITO,CODMUNOCOR,LOCOCOR,CAUSABAS,SEXO,IDADE,ESC2010,OCUP,PESO,LINHAA,LINHAB,LINHAC,FONTEINV,ACIDTRAB
0,83298209,5085680,18797155,AutomÃ³vel,FORD/FIESTA HA 1.6L SE A,2013,Condutor,ileso,31.0,Feminino,Brasil,NÃ£o Informado,Quinta,00:05:00,RJ,101,327.0,NITEROI,Outras,ColisÃ£o traseira,Sem VÃ­timas,Plena noite,Decrescente,Ceu Claro,Dupla,Reta,Urbano,2015,2,0,0,0,2,0,0,2,Transporte UtilitÃ¡rio e Familiar,2015-01-01,Ileso,2015-01-01,31.0,FEMININO,1012015,08:50,Não Informado,Hospital,Pedestre traum colis automov pickup caminhon V03,Feminino,31 Anos,Não Informado,Não Informado,Não Informado,Traum de regiao NE do corpo,Não Informado,Pedestre traum colis automov pickup caminhon V03,Não Informado,Não Informado
1,83298209,5085680,18797155,AutomÃ³vel,FORD/FIESTA HA 1.6L SE A,2013,Condutor,ileso,31.0,Feminino,Brasil,NÃ£o Informado,Quinta,00:05:00,RJ,101,327.0,NITEROI,Outras,ColisÃ£o traseira,Sem VÃ­timas,Plena noite,Decrescente,Ceu Claro,Dupla,Reta,Urbano,2015,2,0,0,0,2,0,0,2,Transporte UtilitÃ¡rio e Familiar,2015-01-01,Ileso,2015-01-01,31.0,FEMININO,1012015,03:30,Não Informado,Hospital,Ocup automovel traum outr acid transp e NE,Feminino,31 Anos,Não Informado,Não Informado,Não Informado,Algumas complic precoces dos traum NCOP,Ocup automovel traum outr acid transp e NE,Não Informado,Não Informado,Não Informado
2,83298209,5085683,18797156,AutomÃ³vel,VW/PARATI GLI 1.8 ...,1996,Condutor,ileso,54.0,Masculino,Brasil,NÃ£o Informado,Quinta,00:05:00,RJ,101,327.0,NITEROI,Outras,ColisÃ£o traseira,Sem VÃ­timas,Plena noite,Decrescente,Ceu Claro,Dupla,Reta,Urbano,2015,2,0,0,0,2,0,0,2,Transporte UtilitÃ¡rio e Familiar,2015-01-01,Ileso,2015-01-01,54.0,MASCULINO,1012015,Não Informado,Não Informado,Via pública,Ciclista traum colis automov pickup caminhon V13,Masculino,54 Anos,Não Informado,Não Informado,Não Informado,Algumas complic precoces dos traum NCOP,Outr traum do torax e os NE,Ciclista traum colis automov pickup caminhon V13,Não Informado,Não Informado
3,83298220,5090798,18799573,UtilitÃ¡rio,I/SSANGYONG KYRONM200XDI,2011,Condutor,ileso,53.0,Masculino,Brasil,Rio De Janeiro,Quinta,01:45:00,RJ,40,64.0,PETROPOLIS,Outras,ColisÃ£o com objeto fixo,Sem VÃ­timas,Plena noite,Crescente,Nublado,Dupla,Reta,Urbano,2015,2,0,0,0,2,0,0,2,Transporte UtilitÃ¡rio e Familiar,2015-01-01,Ileso,2015-01-01,53.0,MASCULINO,1012015,02:50,Não Informado,Outros,Pedestre traum colis automov pickup caminhon V03,Masculino,53 Anos,Não Informado,Não Informado,Não Informado,Traum intracraniano,Traum de outr orgaos intratoracicos e dos NE S27,Pedestre traum colis automov pickup caminhon V03,Não Informado,Não Informado
4,83298221,5085742,18797179,AutomÃ³vel,GM/CORSA CLASSIC,2003,Condutor,ferido leve,27.0,Masculino,Brasil,Icara,Quinta,02:50:00,SC,101,356.1,SANGAO,Falta de atenÃ§Ã£o,SaÃ­da de Pista,Com VÃ­timas Feridas,Plena noite,Crescente,Ceu Claro,Dupla,Reta,Urbano,2015,4,0,4,0,0,0,4,1,Transporte UtilitÃ¡rio e Familiar,2015-01-01,Ferido Leve,2015-01-01,27.0,MASCULINO,1012015,05:50,Não Informado,Via pública,Pedestre traum outr acid transp e NE,Masculino,27 Anos,Não Informado,Não Informado,Não Informado,Traum intracraniano,Pedestre traum outr acid transp e NE,Não Informado,Não Informado,Não Informado

In [19]:
# Configurar o pandas para não ocultar colunas ao exibir
pd.set_option('display.max_columns', None)

# Exibir a lista completa de colunas unificadas
print("Colunas no DataFrame unificado (dados_cruzados):")
for i, col in enumerate(dados_cruzados.columns, 1):
    print(f"{i}. {col}")

# Exibir as primeiras 3 linhas com todas as colunas visíveis
display(dados_cruzados.head(10))

Colunas no DataFrame unificado (dados_cruzados):
1. id
2. pesid
3. id_veiculo
4. tipo_veiculo
5. marca
6. ano_fabricacao_veiculo
7. tipo_envolvido
8. estado_fisico
9. idade
10. sexo
11. nacionalidade
12. naturalidade
13. dia_semana
14. horario
15. uf
16. br
17. km
18. municipio
19. causa_acidente
20. tipo_acidente
21. classificacao_acidente
22. fase_dia
23. sentido_via
24. condicao_metereologica
25. tipo_pista
26. tracado_via
27. uso_solo
28. ano
29. pessoas
30. mortos
31. feridos_leves
32. feridos_graves
33. ilesos
34. ignorados
35. feridos
36. veiculos
37. categorias
38. data
39. gravidade_geral
40. data_padrao
41. idade_padrao
42. sexo_padrao
43. DTOBITO
44. HORAOBITO
45. CODMUNOCOR
46. LOCOCOR
47. CAUSABAS
48. SEXO
49. IDADE
50. ESC2010
51. OCUP
52. PESO
53. LINHAA
54. LINHAB
55. LINHAC
56. FONTEINV
57. ACIDTRAB

,id,pesid,id_veiculo,tipo_veiculo,marca,ano_fabricacao_veiculo,tipo_envolvido,estado_fisico,idade,sexo,nacionalidade,naturalidade,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,classificacao_acidente,fase_dia,sentido_via,condicao_metereologica,tipo_pista,tracado_via,uso_solo,ano,pessoas,mortos,feridos_leves,feridos_graves,ilesos,ignorados,feridos,veiculos,categorias,data,gravidade_geral,data_padrao,idade_padrao,sexo_padrao,DTOBITO,HORAOBITO,CODMUNOCOR,LOCOCOR,CAUSABAS,SEXO,IDADE,ESC2010,OCUP,PESO,LINHAA,LINHAB,LINHAC,FONTEINV,ACIDTRAB
0,83298209,5085680,18797155,AutomÃ³vel,FORD/FIESTA HA 1.6L SE A,2013,Condutor,ileso,31.0,Feminino,Brasil,NÃ£o Informado,Quinta,00:05:00,RJ,101,327.0,NITEROI,Outras,ColisÃ£o traseira,Sem VÃ­timas,Plena noite,Decrescente,Ceu Claro,Dupla,Reta,Urbano,2015,2,0,0,0,2,0,0,2,Transporte UtilitÃ¡rio e Familiar,2015-01-01,Ileso,2015-01-01,31.0,FEMININO,1012015,08:50,Não Informado,Hospital,Pedestre traum colis automov pickup caminhon V03,Feminino,31 Anos,Não Informado,Não Informado,Não Informado,Traum de regiao NE do corpo,Não Informado,Pedestre traum colis automov pickup caminhon V03,Não Informado,Não Informado
1,83298209,5085680,18797155,AutomÃ³vel,FORD/FIESTA HA 1.6L SE A,2013,Condutor,ileso,31.0,Feminino,Brasil,NÃ£o Informado,Quinta,00:05:00,RJ,101,327.0,NITEROI,Outras,ColisÃ£o traseira,Sem VÃ­timas,Plena noite,Decrescente,Ceu Claro,Dupla,Reta,Urbano,2015,2,0,0,0,2,0,0,2,Transporte UtilitÃ¡rio e Familiar,2015-01-01,Ileso,2015-01-01,31.0,FEMININO,1012015,03:30,Não Informado,Hospital,Ocup automovel traum outr acid transp e NE,Feminino,31 Anos,Não Informado,Não Informado,Não Informado,Algumas complic precoces dos traum NCOP,Ocup automovel traum outr acid transp e NE,Não Informado,Não Informado,Não Informado
2,83298209,5085683,18797156,AutomÃ³vel,VW/PARATI GLI 1.8 ...,1996,Condutor,ileso,54.0,Masculino,Brasil,NÃ£o Informado,Quinta,00:05:00,RJ,101,327.0,NITEROI,Outras,ColisÃ£o traseira,Sem VÃ­timas,Plena noite,Decrescente,Ceu Claro,Dupla,Reta,Urbano,2015,2,0,0,0,2,0,0,2,Transporte UtilitÃ¡rio e Familiar,2015-01-01,Ileso,2015-01-01,54.0,MASCULINO,1012015,Não Informado,Não Informado,Via pública,Ciclista traum colis automov pickup caminhon V13,Masculino,54 Anos,Não Informado,Não Informado,Não Informado,Algumas complic precoces dos traum NCOP,Outr traum do torax e os NE,Ciclista traum colis automov pickup caminhon V13,Não Informado,Não Informado
3,83298220,5090798,18799573,UtilitÃ¡rio,I/SSANGYONG KYRONM200XDI,2011,Condutor,ileso,53.0,Masculino,Brasil,Rio De Janeiro,Quinta,01:45:00,RJ,40,64.0,PETROPOLIS,Outras,ColisÃ£o com objeto fixo,Sem VÃ­timas,Plena noite,Crescente,Nublado,Dupla,Reta,Urbano,2015,2,0,0,0,2,0,0,2,Transporte UtilitÃ¡rio e Familiar,2015-01-01,Ileso,2015-01-01,53.0,MASCULINO,1012015,02:50,Não Informado,Outros,Pedestre traum colis automov pickup caminhon V03,Masculino,53 Anos,Não Informado,Não Informado,Não Informado,Traum intracraniano,Traum de outr orgaos intratoracicos e dos NE S27,Pedestre traum colis automov pickup caminhon V03,Não Informado,Não Informado
4,83298221,5085742,18797179,AutomÃ³vel,GM/CORSA CLASSIC,2003,Condutor,ferido leve,27.0,Masculino,Brasil,Icara,Quinta,02:50:00,SC,101,356.1,SANGAO,Falta de atenÃ§Ã£o,SaÃ­da de Pista,Com VÃ­timas Feridas,Plena noite,Crescente,Ceu Claro,Dupla,Reta,Urbano,2015,4,0,4,0,0,0,4,1,Transporte UtilitÃ¡rio e Familiar,2015-01-01,Ferido Leve,2015-01-01,27.0,MASCULINO,1012015,05:50,Não Informado,Via pública,Pedestre traum outr acid transp e NE,Masculino,27 Anos,Não Informado,Não Informado,Não Informado,Traum intracraniano,Pedestre traum outr acid transp e NE,Não Informado,Não Informado,Não Informado
5,83298221,5085742,18797179,AutomÃ³vel,GM/CORSA CLASSIC,2003,Condutor,ferido leve,27.0,Masculino,Brasil,Icara,Quinta,02:50:00,SC,101,356.1,SANGAO,Falta de atenÃ§Ã£o,SaÃ­da de Pista,Com VÃ­timas Feridas,Plena noite,Crescente,Ceu Claro,Dupla,Reta,Urbano,2015,4,0,4,0,0,0,4,1,Transporte UtilitÃ¡rio e Familiar,2015-01-01,Ferido Leve,2015-01-01,27.0,MASCULINO,1012015,16:00,Não Informado,Hospital,Motociclista traum outr acid transp e NE,Masculino,27 Anos,Não Informado,Não Informado,Não Informado,Motociclista traum outr acid transp e NE,Motociclista traum outr acid transp e NE,Não Informado,Não Informado,Não Informado
6,83298221,5085742,18797179,AutomÃ³vel,GM/CORSA CLASSIC,2003,Condutor,ferido leve,27.0,Masculino,Brasil,Icara,Quinta,02:50:00,SC,101,356.1,SANGAO,Falta de atenÃ§Ã£o,SaÃ­da de Pista,Com VÃ­timas Feridas,Plena noite,Crescente,Ceu Claro,Dupla,Reta,Urbano,2015,4,0,4,0,0,0,4,1,Transporte UtilitÃ¡rio e Familiar,2015-01-01,Ferido Leve,2015-01-01,27.0,MASCULINO,1012015,Não Informado,Não Informado,Outros,Acid trans tipo espec desconh mod transp vit V87,Masculino,27 Anos,Não Informado,Não Informado,Não Informado,Não Informado,Não Informado,Outr traum da cabeca e os NE,Não Informado,Não Informado
7,83298221,5085745,18797179,AutomÃ³vel,GM/CORSA CLASSIC,2003,Passageiro,ferido leve,17.0,Masculino,Brasil,Icara,Quinta,02:50:00,SC,101,356.1,SANGAO,Falta de atenÃ§Ã£o,SaÃ­da de Pista,Com VÃ­timas Feridas,Plena noite,Crescente,Ceu Claro,Dupla,Reta,Urbano,2015,4,0,4,0,0,0,4,1,Transporte UtilitÃ¡rio e Familiar,2015-01-01,Ferido Leve,2015-01-01,17.0,MASCULINO,1012015,14:18,Não Informado,Via pública,Motocicl traum colis veic transp pesado onib V24,Masculino,17 Anos,Não Informado,Não Informado,Não Informado,Traum intracraniano,Frat do cranio e dos ossos da face,Frat do femur,Não Informado,Não Informado
8,83298222,5085725,18797172,CaminhÃ£o,M.BENZ/710 ...,1997,Condutor,ileso,33.0,Masculino,Brasil,Alvorada,Quinta,02:50:00,RS,101,25.9,TRES CACHOEIRAS,Falta de atenÃ§Ã£o,SaÃ­da de Pista,Sem VÃ­timas,Plena noite,Decrescente,Nublado,Dupla,Reta,Urbano,2015,1,0,0,0,1,0,0,1,Carga e Transporte Pesado,2015-01-01,Ileso,2015-01-01,33.0,MASCULINO,1012015,Não Informado,Não Informado,Via pública,Ocup automovel traum outr acid transp e NE,Masculino,33 Anos,Não Informado,Não Informado,Não Informado,Traum mult NE,Ocup automovel traum outr acid transp e NE,Não Informado,Não Informado,Não Informado
9,83298222,5085725,18797172,CaminhÃ£o,M.BENZ/710 ...,1997,Condutor,ileso,33.0,Masculino,Brasil,Alvorada,Quinta,02:50:00,RS,101,25.9,TRES CACHOEIRAS,Falta de atenÃ§Ã£o,SaÃ­da de Pista,Sem VÃ­timas,Plena noite,Decrescente,Nublado,Dupla,Reta,Urbano,2015,1,0,0,0,1,0,0,1,Carga e Transporte Pesado,2015-01-01,Ileso,2015-01-01,33.0,MASCULINO,1012015,Não Informado,Não Informado,Via pública,Motociclista traum acid transp s/colis,Masculino,33 Anos,Não Informado,Não Informado,Não Informado,Traum mult NE,Motociclista traum acid transp s/colis,Não Informado,Não Informado,Não Informado